function ClientsView({data}:{data:DashboardData}){
 const [search,setSearch]=React.useState(''); const [status,setStatus]=React.useState('Active');
 const [selected,setSelected]=React.useState(null as ClientRecord|null); const [history,setHistory]=React.useState([] as EntityHistoryEvent[]); const [historyBusy,setHistoryBusy]=React.useState(false); const [historyError,setHistoryError]=React.useState(''); const [equipmentFilter,setEquipmentFilter]=React.useState('all' as 'all'|number);
 const rows=data.clients.filter(x=>(status==='All'||(status==='Active'&&x.active)||(status==='Inactive'&&!x.active))&&(x.code+' '+x.name+' '+x.contact+' '+x.mobile+' '+x.email+' '+x.city+' '+x.state).toLowerCase().includes(search.toLowerCase()));
 const relatedEquipment=selected?data.equipment.filter(e=>(e.clientId!=null?e.clientId===selected.id:e.client===selected.name)):[];
 const relatedServices=selected?data.services.filter(s=>(s.clientId!=null?s.clientId===selected.id:s.client===selected.name)):[];
 const selectedEquipment=equipmentFilter==='all'?null:relatedEquipment.find(e=>e.id===equipmentFilter)||null;
 const filteredServices=equipmentFilter==='all'?relatedServices:relatedServices.filter(s=>s.equipmentId===equipmentFilter);
 const serviceIds=new Set(filteredServices.map(s=>s.serviceId));
 const filteredHistory=equipmentFilter==='all'?history:history.filter(ev=>serviceIds.has(ev.serviceId));
 const openClient=async(x:ClientRecord)=>{setSelected(x);setEquipmentFilter('all');setHistory([]);setHistoryError('');setHistoryBusy(true);try{setHistory(await ServixApi.getClientHistory(x.id))}catch(e:any){setHistoryError(e?.message||String(e))}finally{setHistoryBusy(false)}};
 const historyRows=filteredHistory.map(ev=>({dateTime:ev.createdAt,user:ev.actor,action:ev.eventType,serviceId:ev.serviceId,details:ev.note||([ev.oldValue,ev.newValue].filter(Boolean).join(' → '))||'Record activity',context:ev.equipment+(ev.serialNumber?' • S/N '+ev.serialNumber:'')+' • '+ev.reason,status:ev.serviceStatus}));
 return <div className="module-content module-list-view">
  <PageHeader title="Clients" subtitle="One client record can hold many devices; each device retains its own repeat-service history"/>
  <Toolbar><SearchBox value={search} onChange={setSearch} placeholder="Search name, code, mobile, email or city..."/><select className="filter-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="Active">Active Clients</option><option value="All">All Clients</option><option value="Inactive">Inactive</option></select></Toolbar>
  <div className="results-summary"><span><strong>{rows.length}</strong> matching clients</span><span>Open a client to see all registered devices and choose an individual device history.</span></div>
  <section className="table-card fill-table"><div className="data-table client-table"><div className="tr th"><span>Client</span><span>Contact</span><span>Location</span><span>Equipment</span><span>Service Calls</span><span>Status</span></div>{rows.map(x=><button className="tr record-row" key={x.id} onClick={()=>openClient(x)}><span><strong className="linkish">{x.name}</strong><small>{x.code}</small></span><span><strong>{x.contact||'—'}</strong><small>{[x.mobile,x.email].filter(Boolean).join(' • ')||'No contact details'}</small></span><span>{x.city||'—'}<small>{x.state}</small></span><span><strong>{x.equipmentCount}</strong><small>registered</small></span><span><strong>{x.serviceCount}</strong><small>total calls</small></span><span><StatusBadge value={x.active?'Active':'Inactive'}/></span></button>)}</div>{!rows.length&&<EmptyState title="No matching clients" detail="Adjust the search or status filter. Clients are normally created when a service request is entered."/>}</section>
  {selected&&<Modal title={selected.name} subtitle={selected.code+' • '+relatedEquipment.length+' device(s) • '+relatedServices.length+' service call(s)'} onClose={()=>setSelected(null)} wide className="client-profile-modal">
   <div className="client-compact-profile">
    <section className="client-summary-strip">
     <div><span className="eyebrow">CLIENT</span><h3>{selected.name}</h3><p>{selected.contact||'No contact person'}{selected.mobile?' • '+selected.mobile:''}{selected.email?' • '+selected.email:''}</p></div>
     <div className="client-summary-metrics"><span><small>Devices</small><strong>{relatedEquipment.length}</strong></span><span><small>Services</small><strong>{relatedServices.length}</strong></span><span><small>Open</small><strong>{relatedServices.filter(s=>s.status!=='Closed').length}</strong></span><StatusBadge value={selected.active?'Active':'Inactive'}/></div>
    </section>

    <section className="client-device-section">
     <div className="client-section-title"><div><h4>Registered Equipment</h4><p>Choose a device to see only that device's Service IDs and history.</p></div></div>
     <div className="client-device-grid">
      <button type="button" className={'client-device-card all '+(equipmentFilter==='all'?'active':'')} onClick={()=>setEquipmentFilter('all')}><span className="client-device-icon"><Icon name="equipment" size={18}/></span><span><strong>All Devices</strong><small>{relatedEquipment.length+' registered • '+relatedServices.length+' service calls'}</small></span></button>
      {relatedEquipment.map(e=><button type="button" className={'client-device-card '+(equipmentFilter===e.id?'active':'')} key={e.id} onClick={()=>setEquipmentFilter(e.id)}><span className="client-device-icon"><Icon name="equipment" size={18}/></span><span className="client-device-copy"><strong>{e.make||e.type} {e.model}</strong><small>{e.servixEquipmentId+' • S/N '+(e.serialNumber||'—')}</small><em>{e.serviceCount+' service visit(s) • '+e.coverage}</em></span><Icon name="chevron" size={15}/></button>)}
     </div>
    </section>

    <section className="client-history-section">
     <div className="client-history-head"><div><h4>{selectedEquipment?(selectedEquipment.make+' '+selectedEquipment.model).trim()+' History':'Client Service History'}</h4><p>{selectedEquipment?selectedEquipment.servixEquipmentId+' • S/N '+(selectedEquipment.serialNumber||'—'):'All equipment and Service ID activity for this client'}</p></div><div className="history-actions"><span className="soft-chip">{filteredHistory.length} events</span><button type="button" className="small-button history-action-button" disabled={!filteredHistory.length} onClick={()=>printHistoryDocument(selectedEquipment?'Equipment Service History':'Client Service History',selectedEquipment?(selectedEquipment.servixEquipmentId+' • '+selected.name):(selected.name+' • '+selected.code),historyRows,['Services: '+filteredServices.length])}><Icon name="print" size={14}/> Print</button><button type="button" className="small-button history-action-button" disabled={!filteredHistory.length} onClick={()=>historyRowsToCsv((selectedEquipment?selectedEquipment.servixEquipmentId:selected.code)+'-history',historyRows)}><Icon name="export" size={14}/> CSV</button></div></div>
     <div className="client-service-strip">{filteredServices.slice(0,8).map(s=><div key={s.id}><span><strong>{s.serviceId}</strong><small>{s.openedDate+' • '+s.reason}</small></span><StatusBadge value={s.status}/></div>)}{!filteredServices.length&&<p className="quiet-empty">No Service Calls for this selection.</p>}</div>
     {historyBusy?<div className="history-loading"><div className="boot-spinner"/><span>Loading history…</span></div>:historyError?<div className="form-error">{historyError}</div>:<div className="simple-history-list">{filteredHistory.map(ev=>{const dt=splitAuditDateTime(ev.createdAt);return <div className="simple-history-row" key={ev.serviceId+'-'+ev.id}><div className="simple-history-time"><strong>{dt.date}</strong><small>{dt.time||'—'}</small></div><div className="simple-history-event"><div><strong>{ev.eventType}</strong><span className="history-service-id">{ev.serviceId}</span></div><p>{ev.note||([ev.oldValue,ev.newValue].filter(Boolean).join(' → '))||'Record activity'}</p><small>{ev.actor+' • '+ev.equipment+(ev.serialNumber?' • S/N '+ev.serialNumber:'')}</small></div><StatusBadge value={ev.serviceStatus}/></div>)}{!filteredHistory.length&&!historyBusy&&<p className="quiet-empty">No history recorded for this selection yet.</p>}</div>}
    </section>
   </div>
  </Modal>}
 </div>;
}