function CoverageView({data,onOpenService,onRefresh}:{data:DashboardData;onOpenService:(s:ServiceCall)=>void;onRefresh:()=>void}){
 const [search,setSearch]=React.useState('');const [coverage,setCoverage]=React.useState('All');const [client,setClient]=React.useState('All');const [make,setMake]=React.useState('All');const [expiry,setExpiry]=React.useState('All');const [editing,setEditing]=React.useState(null as EquipmentRecord|null);const [selected,setSelected]=React.useState(null as EquipmentRecord|null);
 const today=new Date().toISOString().slice(0,10);const soon=new Date(Date.now()+30*86400000).toISOString().slice(0,10);const scoped=data.equipment.filter(e=>client==='All'||String(e.clientId)===client);const expiryDate=(e:EquipmentRecord)=>e.coverage==='Warranty'?e.warrantyUntil||'':e.coverage==='AMC'?e.amcUntil||'':'';
 const health=(e:EquipmentRecord)=>e.coverage==='Out of Coverage'?'Uncovered':!expiryDate(e)?'Date missing':expiryDate(e)<today?'Expired':expiryDate(e)<=soon?'Expiring soon':'Active';
 const rows=scoped.filter(e=>filterMatch(e.coverage,coverage)&&filterMatch(e.make,make)&&(expiry==='All'||health(e)===expiry)&&[e.servixEquipmentId,e.client,e.make,e.model,e.serialNumber].join(' ').toLowerCase().includes(search.toLowerCase()));
 const table:ReportTable={headers:['Equipment ID','Client','Make / Model','Serial','Coverage','Coverage Status','Warranty Until','AMC Until','Service Calls'],rows:rows.map(e=>[e.servixEquipmentId,e.client,e.make+' '+e.model,e.serialNumber,e.coverage,health(e),e.warrantyUntil||'',e.amcUntil||'',data.services.filter(s=>s.equipmentId===e.id).length])};
 const changes=selected?(data.operations?.coverageHistory||[]).filter(h=>h.equipmentId===selected.id):[];const services=selected?data.services.filter(s=>s.equipmentId===selected.id):[];
 return <div className="module-content coverage-workspace"><PageHeader title="Warranty / AMC" subtitle="Manage protection, renewals and the coverage recorded at every service visit" actions={<ExportActions title="Coverage and Expiry Report" table={table} meta={['Coverage: '+coverage,'Expiry status: '+expiry]}/>}/>
 <div className="coverage-health-grid">{['Active','Expiring soon','Expired','Uncovered','Date missing'].map(v=><button key={v} className={'coverage-health '+(expiry===v?'selected':'')} onClick={()=>setExpiry(expiry===v?'All':v)}><span>{v}</span><strong>{scoped.filter(e=>health(e)===v).length}</strong><small>{v==='Expiring soon'?'Next 30 days':v==='Date missing'?'Review expiry date':'Equipment records'}</small></button>)}</div>
 <Toolbar><SearchBox value={search} onChange={setSearch}/><SelectFilter label="Coverage" value={coverage} onChange={setCoverage} values={['Warranty','AMC','Out of Coverage']}/><label className="labeled-filter"><span>Client</span><select aria-label="Coverage client" value={client} onChange={e=>{setClient(e.target.value);setMake('All')}}><option value="All">All Clients</option>{data.clients.map(c=><option key={c.id} value={String(c.id)}>{c.name}</option>)}</select></label><SelectFilter label="Make" value={make} onChange={setMake} values={options(scoped.map(e=>e.make))}/><SelectFilter label="Expiry status" value={expiry} onChange={setExpiry} values={['Active','Expiring soon','Expired','Uncovered','Date missing']}/><button className="text-button" onClick={()=>{setSearch('');setCoverage('All');setClient('All');setMake('All');setExpiry('All')}}>Reset</button></Toolbar>
 <div className="results-summary">{rows.length} matching equipment • renewal changes are recorded in coverage history</div>
 <section className="table-card coverage-register"><div className="coverage-register-row heading"><span>Equipment / Serial</span><span>Client</span><span>Protection</span><span>Expiry / Renewal</span><span>Actions</span></div>{rows.map(e=><article className="coverage-register-row" key={e.id}><div><strong>{e.make} {e.model}</strong><small>{e.servixEquipmentId} • S/N {e.serialNumber||'—'}</small></div><div><strong>{e.client}</strong><small>{e.location||'No location recorded'}</small></div><div><StatusBadge value={e.coverage}/><small>{data.services.filter(s=>s.equipmentId===e.id).length} service visits</small></div><div><strong className={health(e)==='Expired'?'overdue-text':''}>{health(e)}</strong><small>{expiryDate(e)||'No expiry date'}</small></div><div className="coverage-row-actions"><button className="small-button" onClick={()=>setSelected(e)}>History</button>{canEditRecords()&&<button className="small-button" onClick={()=>setEditing(e)}>Manage</button>}</div></article>)}</section>
 {!rows.length&&<EmptyState title="No matching coverage" detail="Adjust the filters."/>}
 {editing&&<CoverageEditor record={editing} onClose={()=>setEditing(null)} onSaved={onRefresh}/>}
 {selected&&<Modal title={selected.make+' '+selected.model+' • Coverage History'} subtitle={selected.servixEquipmentId+' • '+selected.client} wide onClose={()=>setSelected(null)}><section className="profile-hero"><div><h3>{selected.coverage}</h3><p>Warranty until: {selected.warrantyUntil||'Not recorded'} • AMC until: {selected.amcUntil||'Not recorded'}</p></div><StatusBadge value={health(selected)}/></section><h4>Coverage Changes / Renewals</h4>{changes.length?<div className="coverage-change-list">{changes.map(h=><article key={h.id}><strong>{h.createdAt} • {h.actor}</strong><p>{h.before.coverage||'Not recorded'} → {h.after.coverage}</p><small>Warranty: {h.before.warrantyUntil||'—'} → {h.after.warrantyUntil||'—'} • AMC: {h.before.amcUntil||'—'} → {h.after.amcUntil||'—'}</small></article>)}</div>:<p className="quiet-empty">No coverage changes recorded yet. Existing service visits retain their original coverage below.</p>}<h4>Coverage at Each Service Visit</h4><ExportActions title={selected.servixEquipmentId+' Coverage History'} table={{headers:['Date','User','Previous Coverage','New Coverage','Previous Warranty','New Warranty','Previous AMC','New AMC'],rows:changes.map(h=>[h.createdAt,h.actor,h.before.coverage||'',h.after.coverage,h.before.warrantyUntil||'',h.after.warrantyUntil||'',h.before.amcUntil||'',h.after.amcUntil||''])}}/><LinkedServiceTable rows={services} onOpen={onOpenService}/></Modal>}
 </div>
}
function CoverageEditor({record,onClose,onSaved}:{record:EquipmentRecord;onClose:()=>void;onSaved:()=>void}){
 const [draft,setDraft]=React.useState({...record,warrantyUntil:record.warrantyUntil||'',amcUntil:record.amcUntil||''});const [busy,setBusy]=React.useState(false);const [error,setError]=React.useState('');
 return <Modal title="Manage Warranty / AMC" subtitle={record.servixEquipmentId+' • '+record.client} onClose={()=>!busy&&onClose()} footer={<><button className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await OperationsApi.save('equipment',draft);await onSaved();onClose()}catch(e:any){setError(e.message||String(e))}finally{setBusy(false)}}}>{busy?'Saving…':'Save Coverage'}</button></>}><section className="profile-hero"><div><h3>{record.make} {record.model}</h3><p>S/N {record.serialNumber||'—'}</p></div></section><div className="form-grid two"><Field label="Current coverage" required><select aria-label="Manage coverage type" value={draft.coverage} onChange={e=>setDraft({...draft,coverage:e.target.value as CoverageType})}>{['Warranty','AMC','Out of Coverage'].map(v=><option key={v}>{v}</option>)}</select></Field>{[{key:'warrantyUntil',label:'Warranty expiry'},{key:'amcUntil',label:'AMC expiry / renewal'}].map(f=><Field key={f.key} label={f.label}><input type="date" value={draft[f.key]} onChange={e=>setDraft({...draft,[f.key]:e.target.value})}/></Field>)}</div><p className="quiet-empty">Renew by updating the expiry date. Previous coverage and dates remain in the change history; service visits retain coverage recorded at the time.</p>{error&&<div className="form-error">{error}</div>}</Modal>
}
