function DashboardView({data,onNavigate,onSync}:{data:DashboardData,onNavigate:(m:ModuleKey,q?:Partial<ServiceQuery>)=>void,onSync:()=>void}){
 const counts={open:data.services.filter(s=>s.status==='Open').length,inProgress:data.services.filter(s=>s.status==='In Progress').length,pending:data.services.filter(s=>s.status==='Pending').length,closed:data.services.filter(s=>s.status==='Closed').length};
 const overdue=data.services.filter(s=>s.status!=='Closed'&&s.dueDate&&s.dueDate<new Date().toISOString().slice(0,10)).length;
 const monthKeys=Array.from({length:12},(_,i)=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-(11-i));return d.toISOString().slice(0,7)});const trend=monthKeys.map(k=>data.services.filter(s=>s.openedDate.startsWith(k)).length);const followups=data.services.filter(s=>s.status!=='Closed'&&s.followUpDate&&s.followUpDate<=new Date().toISOString().slice(0,10)).length;
 const coverage=['Warranty','AMC','Out of Coverage'].map((label,i)=>({label,value:data.services.filter(s=>s.coverage===label).length,tone:['seg-blue','seg-green','seg-amber'][i]}));
 const oldTopClients=Object.entries(data.services.reduce((a:any,s)=>{a[s.client]=(a[s.client]||0)+1;return a},{})).sort((a:any,b:any)=>b[1]-a[1]).slice(0,5).map(([label,value]:any)=>({label,value}));
 const oldTopParts=Object.entries(data.partUsage.reduce((a:any,p)=>{a[p.itemName]=(a[p.itemName]||0)+p.quantity;return a},{})).sort((a:any,b:any)=>b[1]-a[1]).slice(0,5).map(([label,value]:any)=>({label,value}));
 return <div className="module-content dashboard-view">
  <PageHeader title="Dashboard" subtitle="Live overview of service operations and incoming work" actions={<button className="primary-button" onClick={()=>onNavigate('service-calls')}><Icon name="plus"/> Manual Service Call</button>}/>
  <div className="kpi-grid">
   <KpiCard label="Open" value={counts.open} icon="service" tone="blue" onClick={()=>onNavigate('service-calls',{status:'Open'})}/>
   <KpiCard label="In Progress" value={counts.inProgress} icon="service" tone="orange" onClick={()=>onNavigate('service-calls',{status:'In Progress'})}/>
   <KpiCard label="Pending" value={counts.pending} icon="bell" tone="amber" onClick={()=>onNavigate('service-calls',{status:'Pending'})}/>
   <KpiCard label="Closed" value={counts.closed} icon="shield" tone="green" onClick={()=>onNavigate('service-calls',{status:'Closed'})}/>
   <KpiCard label="Overdue" value={overdue} icon="bell" tone="red" onClick={()=>onNavigate('service-calls',{due:'Overdue'})}/>
  </div>
  <div className="dashboard-grid two">
   <ServiceTrendCard data={data} onNavigate={onNavigate}/>
   <section className="card coverage-summary-card"><div className="card-head"><div><h3>Coverage Mix</h3><p>Warranty, AMC and out-of-coverage calls</p></div></div><Donut segments={coverage} totalLabel="Calls"/></section>
  </div>
  <div className="dashboard-grid three">
   <section className={`card sync-card ${data.sync.status==='overdue'?'attention':''}`}><div className="card-head"><div><h3>Google Form Sync</h3><p>Incoming request source</p></div><StatusBadge value={data.sync.status==='up-to-date'?'Up to date':data.sync.status==='not-configured'?'Not configured':'Warning'}/></div><div className="sync-time"><span>Last successful sync</span><strong>{data.sync.lastSuccessfulSync||'Not yet synced'}</strong></div><div className="sync-stat"><span>{data.sync.newCount} new requests</span><button className="secondary-button" onClick={onSync}><Icon name="refresh"/> Sync Now</button></div></section>
   <section className="card"><div className="card-head"><div><h3>Recent Incoming Requests</h3><p>Needs office review</p></div><button className="text-button" onClick={()=>onNavigate('intake')}>View all</button></div><div className="compact-list">{data.intake.filter(x=>x.status==='New'||x.status==='Reviewed').slice(0,4).map(x=><button key={x.id} onClick={()=>onNavigate('intake')}><span><strong>{x.client}</strong><small>{x.equipment}</small></span><StatusBadge value={x.status}/></button>)}</div></section>
   <section className="card"><div className="card-head"><div><h3>Recent Service Calls</h3><p>Newest activity first</p></div><button className="text-button" onClick={()=>onNavigate('service-calls')}>View all</button></div><div className="compact-list">{data.services.slice(0,4).map(x=><button key={x.id} onClick={()=>onNavigate('service-calls')}><span><strong>{x.serviceId}</strong><small>{x.client} • {x.equipment}</small></span><StatusBadge value={x.status}/></button>)}</div></section>
  </div>
  <div className="dashboard-grid three">
   <section className="card"><div className="card-head"><div><h3>Alerts / Reminders</h3><p>Items needing attention</p></div></div><div className="alerts"><div className="alert amber"><Icon name="calendar"/><span><strong>{followups} follow-ups due</strong><small>Check next actions recorded on Service Calls</small></span></div><div className="alert red"><Icon name="bell"/><span><strong>{overdue} service calls overdue</strong><small>Review due dates and pending work</small></span></div><div className="alert amber"><Icon name="calibration"/><span><strong>{(data.operations?.calibrations||[]).filter(r=>r.nextDue&&r.nextDue<new Date().toISOString().slice(0,10)).length} calibrations overdue</strong><small>Track due and upcoming calibrations</small></span></div><div className="alert blue"><Icon name="shield"/><span><strong>{data.equipment.filter(e=>{const d=e.coverage==='Warranty'?e.warrantyUntil:e.coverage==='AMC'?e.amcUntil:'';return d&&d<new Date().toISOString().slice(0,10)}).length} coverage records expired</strong><small>Warranty / AMC expiry monitoring</small></span></div></div></section>
   <DashboardRanking title="Top Clients" subtitle="Clients with the most Service Calls" unit="calls" items={data.clients.map(c=>({label:c.name,value:data.services.filter(s=>s.clientId===c.id).length,detail:[c.city,c.state].filter(Boolean).join(', '),onClick:()=>onNavigate('service-calls',{client:String(c.id)})})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value)} onAll={()=>onNavigate('clients')}/>
   <DashboardRanking title="Parts Usage" subtitle="Most used items across service visits" unit="units" items={oldTopParts.map(x=>({...x,detail:'Recorded quantity used',onClick:()=>onNavigate('parts')}))} total={data.partUsage.reduce((n,p)=>n+p.quantity,0)} onAll={()=>onNavigate('parts')}/>

  </div>
 </div>;
}

function ServiceTrendCard({data,onNavigate}:{data:DashboardData;onNavigate:(m:ModuleKey,q?:Partial<ServiceQuery>)=>void}){
 const [period,setPeriod]=React.useState(6);const now=new Date();const months=Array.from({length:period},(_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-period+1+i,1);const key=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');const calls=data.services.filter(s=>s.openedDate.startsWith(key));return {key,label:d.toLocaleDateString('en-IN',{month:'short'}),year:d.getFullYear(),total:calls.length,closed:calls.filter(s=>s.status==='Closed').length,active:calls.filter(s=>s.status!=='Closed').length}});const total=months.reduce((n,m)=>n+m.total,0),closed=months.reduce((n,m)=>n+m.closed,0),peak=Math.max(1,...months.map(m=>m.total));const current=months[months.length-1],previous=months[months.length-2];const delta=current.total-previous.total;const change=previous.total?Math.round(delta/previous.total*100)+'%':current.total?'New activity':'No change';const ticks=Array.from({length:5},(_,i)=>Math.ceil(peak/4)*i);const max=ticks[4];
 return <section className="card service-trend-card"><div className="card-head"><div><h3>Service Calls Trend</h3><p>Monthly intake • current status of each month's calls</p></div><div className="trend-period">{[6,12].map(n=><button key={n} className={period===n?'active':''} onClick={()=>setPeriod(n)}>{n} months</button>)}</div></div><div className="trend-metrics"><div><small>Calls in period</small><strong>{total}</strong></div><div><small>Closed</small><strong>{closed}<em>{total?Math.round(closed/total*100):0}% of period</em></strong></div><div><small>This month</small><strong>{current.total}<em>{change} vs previous month{now.getDate()<28?' • month to date':''}</em></strong></div></div><div className="trend-chart"><div className="trend-axis">{ticks.slice().reverse().map(t=><span key={t}>{t}</span>)}</div><div className="trend-plot"><div className="trend-grid">{ticks.map(t=><i key={t}/>)}</div><div className="trend-columns">{months.map(m=><button key={m.key} className={'trend-column'+(m.key===current.key?' current':'')} onClick={()=>{const [y,mo]=m.key.split('-').map(Number);onNavigate('service-calls',{from:m.key+'-01',to:m.key+'-'+new Date(y,mo,0).getDate()})}} aria-label={m.label+' '+m.year+': '+m.total+' calls, '+m.closed+' closed, '+m.active+' active'} title={m.key+' • '+m.total+' calls • '+m.closed+' closed • '+m.active+' active'}><span className="trend-count">{m.total}</span><span className="trend-stack" style={{height:(m.total/max*100)+'%'}}><i className="trend-active" style={{flex:m.active}}/><i className="trend-closed" style={{flex:m.closed}}/></span><span className="trend-month">{m.label}<small>{m.year}</small></span></button>)}</div></div></div><div className="trend-legend"><span><i className="trend-active"/>Active</span><span><i className="trend-closed"/>Closed</span><small>Click a month to view its Service Calls</small></div>{!total&&<p>No Service Calls recorded in this period.</p>}</section>
}
function DashboardRanking({title,subtitle,unit,items,total,onAll}:{title:string;subtitle:string;unit:string;items:{label:string;value:number;detail:string;onClick:()=>void}[];total?:number;onAll:()=>void}){const sum=total??items.reduce((n,x)=>n+x.value,0);return <section className="card dashboard-ranking"><div className="card-head"><div><h3>{title}</h3><p>{subtitle}</p></div><button className="text-button" onClick={onAll}>View all</button></div><div className="ranking-total"><strong>{sum}</strong><span>{unit} recorded</span><small>Top {Math.min(5,items.length)} shown</small></div><div className="ranking-list">{items.slice(0,5).map((x,i)=><button className="ranking-row" key={x.label+'-'+i} onClick={x.onClick}><span className="ranking-position">{i+1}</span><span className="ranking-info"><strong>{x.label}</strong><small>{x.detail}</small><span className="ranking-track"><i style={{width:(sum?x.value/sum*100:0)+'%'}}/></span></span><span className="ranking-value"><strong>{x.value}</strong><small>{sum?Math.round(x.value/sum*100):0}%</small></span></button>)}</div>{!items.length&&<p>No recorded activity yet.</p>}</section>}
