function DataManagementView({onRefresh}:{onRefresh:()=>void}){
 const [showQa,setShowQa]=React.useState(false); const [busy,setBusy]=React.useState(false); const [message,setMessage]=React.useState('');
 const [destination,setDestination]=React.useState('');const [restorePath,setRestorePath]=React.useState('');const [preview,setPreview]=React.useState(null as RestorePreview|null);
 const backup=async()=>{setBusy(true);setMessage('');try{setMessage('Backup saved: '+await FileApi.backup(destination))}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const choose=async(folder:boolean)=>{setBusy(true);try{const path=await FileApi.choose(folder);if(path){if(folder)setDestination(path);else{setRestorePath(path);setPreview(null)}}}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const reviewRestore=async()=>{setBusy(true);setMessage('');try{setPreview(await FileApi.preview(restorePath))}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const restore=async()=>{if(!preview)return;setBusy(true);try{const result=await FileApi.restore(preview);window.alert(result);window.location.reload()}catch(e:any){setMessage(e?.message||String(e));setPreview(null)}finally{setBusy(false)}};
 const loadQa=async()=>{setBusy(true);setMessage('');try{const result=await ServixApi.loadQaMockData();setMessage(result);await onRefresh();setShowQa(false)}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 return <div className="module-content"><PageHeader title="Data Management" subtitle="Safe import, export, backup and restore — never overwrite silently"/><div className="settings-grid">
  <AutomaticBackupPreferences/>
  <DataExportPanel/>
  <CsvImportPanel onRefresh={onRefresh}/>
  <section className="card"><div className="feature-icon"><Icon name="data"/></div><h3>Backup</h3><p>Complete recovery package containing the SQLite database plus linked photos, PDFs and documents.</p><Field label="Backup folder (optional)"><input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Default: application data / backups"/></Field><div className="attachment-toolbar"><button className="secondary-button" disabled={busy} onClick={()=>choose(true)}>Browse folder</button><button className="primary-button" disabled={busy} onClick={backup}>{busy?'Working…':'Create Backup'}</button></div></section>
  <section className="card"><div className="feature-icon"><Icon name="refresh"/></div><h3>Restore</h3><p>Restore is verified before the live workspace is replaced. Existing data is protected by a pre-restore backup.</p><Field label="Backup file"><input value={restorePath} onChange={e=>{setRestorePath(e.target.value);setPreview(null)}} placeholder="Choose a .servixbackup file"/></Field><div className="attachment-toolbar"><button className="secondary-button" disabled={busy} onClick={()=>choose(false)}>Browse file</button><button className="secondary-button" disabled={busy||!restorePath.trim()} onClick={reviewRestore}>Verify & Preview</button></div></section>
  <section className="card"><div className="feature-icon"><Icon name="service"/></div><h3>QA Test Data</h3><p>Five months of QA5 test data: 8 clients, 12 devices, 60 Service Calls and 120 notes, with coverage, calibration, parts, payments and incoming-status examples. Administrator only; never loads automatically.</p><button className="secondary-button" onClick={()=>setShowQa(true)}>Load QA Test Data</button></section>
 </div>
 {message&&<section className="card"><p style={{overflowWrap:'anywhere'}}>{message}</p></section>}
 {preview&&<Modal title="Restore verified backup" subtitle="Review before replacing this workspace" onClose={()=>!busy&&setPreview(null)} footer={<><button className="secondary-button" disabled={busy} onClick={()=>setPreview(null)}>Cancel</button><button className="primary-button" disabled={busy} onClick={restore}>{busy?'Restoring…':'Create safety backup & Restore'}</button></>}><p>Backup created: {preview.createdAt}</p><p>{preview.clients} clients • {preview.services} Service Calls • {preview.files} files</p><p>Restore replaces current records and accounts. A recovery backup is saved first. You will then sign in using an account from this backup.</p></Modal>}
 {showQa&&<Modal title="Load QA Test Data" subtitle="Testing only — adds clearly marked QA records to this local database" onClose={()=>!busy&&setShowQa(false)} footer={<><button className="secondary-button" disabled={busy} onClick={()=>setShowQa(false)}>Cancel</button><button className="primary-button" disabled={busy} onClick={loadQa}>{busy?'Loading...':'Load Test Records'}</button></>}><div className="sync-warning-copy"><Icon name="bell" size={24}/><p>This adds five months of clearly marked QA5 test records alongside existing data. It does not alter production Service ID numbering and will not duplicate an already loaded QA5 dataset. Run it on a test installation or restore a test backup before using it.</p></div></Modal>}
 </div>;
}