function DataManagementView({onRefresh}:{onRefresh:()=>void}){
 const [showQa,setShowQa]=React.useState(false); const [busy,setBusy]=React.useState(false); const [message,setMessage]=React.useState('');
 const loadQa=async()=>{setBusy(true);setMessage('');try{const result=await ServixApi.loadQaMockData();setMessage(result);await onRefresh();setShowQa(false)}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 return <div className="module-content"><PageHeader title="Data Management" subtitle="Safe import, export, backup and restore — never overwrite silently"/><div className="settings-grid">
  <section className="card"><div className="feature-icon"><Icon name="export"/></div><h3>Export</h3><p>Export selected records, current filtered results, a date range or a full portable data set. CSV remains separate from recovery backup.</p><button className="secondary-button">Open Export</button></section>
  <section className="card"><div className="feature-icon"><Icon name="intake"/></div><h3>Import</h3><p>Choose file → preview → field mapping → validation → duplicate review → deliberate commit.</p><button className="secondary-button">Import CSV</button></section>
  <section className="card"><div className="feature-icon"><Icon name="data"/></div><h3>Backup</h3><p>Complete recovery package containing the SQLite database plus linked photos, PDFs and documents.</p><button className="secondary-button">Create Backup</button></section>
  <section className="card"><div className="feature-icon"><Icon name="refresh"/></div><h3>Restore</h3><p>Restore is verified before the live workspace is replaced. Existing data is protected by a pre-restore backup.</p><button className="secondary-button">Restore Backup</button></section>
  <section className="card"><div className="feature-icon"><Icon name="service"/></div><h3>QA Test Data</h3><p>Administrator-only controlled dataset for duplicate, repeat-service, history, coverage, parts, payment and intake testing. It never loads automatically.</p><button className="secondary-button" onClick={()=>setShowQa(true)}>Load QA Test Data</button>{message&&<p className="about-note">{message}</p>}</section>
 </div>
 {showQa&&<Modal title="Load QA Test Data" subtitle="Testing only — adds clearly marked QA records to this local database" onClose={()=>!busy&&setShowQa(false)} footer={<><button className="secondary-button" disabled={busy} onClick={()=>setShowQa(false)}>Cancel</button><button className="primary-button" disabled={busy} onClick={loadQa}>{busy?'Loading...':'Load Test Records'}</button></>}><div className="sync-warning-copy"><Icon name="bell" size={24}/><p>This will add realistic test clients, equipment, Service Calls, duplicate mobile/email and serial-number cases, history notes, parts usage and intake records. Run this only on a test installation/database.</p></div></Modal>}
 </div>;
}