function EquipmentView({data,initialId,onOpenService,onRefresh}:{data:DashboardData,initialId?:number,onRefresh:()=>void,onOpenService?:(s:ServiceCall)=>void}){
 const [editing,setEditing]=React.useState(null as EquipmentRecord|null);
 const [search,setSearch]=React.useState(''); const [coverage,setCoverage]=React.useState('All');
 const [selected,setSelected]=React.useState(null as EquipmentRecord|null); const [history,setHistory]=React.useState([] as EntityHistoryEvent[]); const [historyBusy,setHistoryBusy]=React.useState(false); const [historyError,setHistoryError]=React.useState('');
 const [clientFilter,setClientFilter]=React.useState('All');const [makeFilter,setMakeFilter]=React.useState('All');const [typeFilter,setTypeFilter]=React.useState('All');const [locationFilter,setLocationFilter]=React.useState('All');const [activity,setActivity]=React.useState('All');const historyRequest=React.useRef(0);
 const rows=data.equipment.filter(x=>(coverage==='All'||x.coverage===coverage)&&(clientFilter==='All'||(x.clientId!=null?String(x.clientId)===clientFilter:x.client===data.clients.find(c=>String(c.id)===clientFilter)?.name))&&(makeFilter==='All'||x.make===makeFilter)&&(typeFilter==='All'||x.type===typeFilter)&&(locationFilter==='All'||x.location===locationFilter)&&(activity==='All'||(activity==='No History'?!data.services.some(s=>s.equipmentId===x.id):data.services.some(s=>s.equipmentId===x.id&&(activity==='Active Calls'?s.status!=='Closed':s.status==='Closed'))))&&(x.servixEquipmentId+' '+x.client+' '+x.make+' '+x.model+' '+x.serialNumber+' '+x.type+' '+x.location).toLowerCase().includes(search.toLowerCase()));
 const relatedServices=selected?data.services.filter(s=>s.equipmentId===selected.id):[];
 const openEquipment=async(x:EquipmentRecord)=>{const request=++historyRequest.current;setSelected(x);setHistory([]);setHistoryError('');setHistoryBusy(true);try{const items=await ServixApi.getEquipmentHistory(x.id);if(request===historyRequest.current)setHistory(items)}catch(e:any){if(request===historyRequest.current)setHistoryError(e?.message||String(e))}finally{if(request===historyRequest.current)setHistoryBusy(false)}};
 React.useEffect(()=>{if(initialId){const e=data.equipment.find(x=>x.id===initialId);if(e)openEquipment(e)}return()=>{historyRequest.current++}},[initialId]);
 return <div className="module-content module-list-view">
  <PageHeader title="Equipment" subtitle="Client-linked equipment registry with repeat-service history and coverage context"/>
  <Toolbar><SearchBox value={search} onChange={setSearch} placeholder="Search SERVIX ID, serial, client, make or model..."/><select className="filter-select" value={coverage} onChange={e=>setCoverage(e.target.value)}><option value="All">All Coverage</option><option>Warranty</option><option>AMC</option><option>Out of Coverage</option></select><select className="filter-select" aria-label="Equipment client" value={clientFilter} onChange={e=>{setClientFilter(e.target.value);setMakeFilter('All');setTypeFilter('All');setLocationFilter('All')}}><option value="All">All Clients</option>{data.clients.map(c=><option value={String(c.id)} key={c.id}>{c.name+' • '+c.code}</option>)}</select>{[{label:'Make',value:makeFilter,set:setMakeFilter,options:data.equipment.filter(e=>clientFilter==='All'||String(e.clientId)===clientFilter).map(e=>e.make)},{label:'Type',value:typeFilter,set:setTypeFilter,options:data.equipment.filter(e=>(clientFilter==='All'||String(e.clientId)===clientFilter)&&filterMatch(e.make,makeFilter)).map(e=>e.type)},{label:'Location',value:locationFilter,set:setLocationFilter,options:data.equipment.filter(e=>(clientFilter==='All'||String(e.clientId)===clientFilter)&&filterMatch(e.make,makeFilter)&&filterMatch(e.type,typeFilter)).map(e=>e.location)}].map(f=><select className="filter-select" aria-label={'Equipment '+f.label.toLowerCase()} key={f.label} value={f.value} onChange={e=>{f.set(e.target.value);if(f.label==='Make'){setTypeFilter('All');setLocationFilter('All')}if(f.label==='Type')setLocationFilter('All')}}><option value="All">All {f.label}s</option>{Array.from(new Set(f.options.filter(Boolean))).sort().map(v=><option key={v}>{v}</option>)}</select>)}<select className="filter-select" aria-label="Equipment activity" value={activity} onChange={e=>setActivity(e.target.value)}>{['All','Active Calls','Closed Calls','No History'].map(c=><option value={c} key={c}>{c==='All'?'All Activity':c}</option>)}</select><button className="text-button" onClick={()=>{setSearch('');setCoverage('All');setClientFilter('All');setMakeFilter('All');setTypeFilter('All');setLocationFilter('All');setActivity('All')}}>Reset Filters</button></Toolbar>
  <div className="results-summary"><span><strong>{rows.length}</strong> matching equipment</span><span>Open equipment to review repeat Service Calls and its full activity timeline.</span></div>
  <section className="table-card fill-table"><div className="data-table equipment-table"><div className="tr th"><span>Equipment ID</span><span>Client</span><span>Make / Model</span><span>Serial Number</span><span>Type / Location</span><span>Coverage</span><span>History</span></div>{rows.map(x=><button className="tr record-row" key={x.id} onClick={()=>openEquipment(x)}><span><strong className="linkish">{x.servixEquipmentId}</strong></span><span><strong>{x.client}</strong></span><span><strong>{x.make||'—'}</strong><small>{x.model||'No model'}</small></span><span>{x.serialNumber||'—'}</span><span>{x.type||'—'}<small>{x.location||'No location'}</small></span><span><StatusBadge value={x.coverage}/></span><span><strong>{x.serviceCount} services</strong><small>{x.lastService?'Last: '+x.lastService:'No previous service'}</small></span></button>)}</div>{!rows.length&&<EmptyState title="No matching equipment" detail="Adjust the search or coverage filter. Equipment is normally registered during service intake."/>}</section>
  {selected&&<Modal title={(selected.make+' '+selected.model).trim()||selected.servixEquipmentId} subtitle={selected.servixEquipmentId+' • Equipment profile'} onClose={()=>{historyRequest.current++;setSelected(null)}} wide className="equipment-profile-modal" footer={<>{canEditRecords()&&<button className="primary-button" onClick={()=>setEditing(selected)}>Edit Equipment</button>}</>}>
   <div className="record-profile">
    <section className="profile-hero"><div><span className="eyebrow">EQUIPMENT</span><h3>{selected.make} {selected.model}</h3><p>{selected.client+' • Serial: '+(selected.serialNumber||'—')+' • '+(selected.type||'Equipment')}</p></div><StatusBadge value={selected.coverage}/></section>
    <div className="profile-metrics"><div><span>Service Calls</span><strong>{relatedServices.length}</strong></div><div><span>Open / Active</span><strong>{relatedServices.filter(s=>s.status!=='Closed').length}</strong></div><div><span>Last Service</span><strong className="metric-text">{selected.lastService||'—'}</strong></div><div><span>Location</span><strong className="metric-text">{selected.location||'—'}</strong></div></div>
    <div className="profile-grid two">
     <section className="profile-panel"><div className="panel-heading"><div><h4>Equipment Details</h4><p>Current registry information</p></div></div><div className="detail-pairs"><div><span>Client</span><strong>{selected.client}</strong></div><div><span>Make</span><strong>{selected.make||'—'}</strong></div><div><span>Model</span><strong>{selected.model||'—'}</strong></div><div><span>Serial Number</span><strong>{selected.serialNumber||'—'}</strong></div><div><span>Type</span><strong>{selected.type||'—'}</strong></div><div><span>Coverage</span><strong>{selected.coverage}</strong></div></div></section>
     <section className="profile-panel"><div className="panel-heading"><div><h4>Service Calls</h4><p>Repeat visits for this exact equipment</p></div><span className="soft-chip">{relatedServices.length}</span></div><LinkedServiceTable rows={relatedServices} onOpen={onOpenService}/></section>
    </div>
    <section className="profile-panel entity-history-panel"><div className="panel-heading"><div><h4>Equipment Activity Timeline</h4><p>All recorded Service ID activity for this exact equipment</p></div><div className="history-actions"><span className="soft-chip">{history.length} events</span><button type="button" className="small-button history-action-button" disabled={!history.length} onClick={()=>{const rows=history.map(ev=>({dateTime:ev.createdAt,user:ev.actor,action:ev.eventType,serviceId:ev.serviceId,details:historyEventDetails(ev),context:ev.reason+' • '+ev.client,status:ev.serviceStatus}));printHistoryDocument('Equipment Service History',selected.servixEquipmentId+' • '+selected.make+' '+selected.model,rows,['Client: '+selected.client,'Serial: '+(selected.serialNumber||'—'),'Coverage: '+selected.coverage+' • Service Calls: '+relatedServices.length])}}><Icon name="print" size={14}/> Print</button><button type="button" className="small-button history-action-button" disabled={!history.length} onClick={()=>{const rows=history.map(ev=>({dateTime:ev.createdAt,user:ev.actor,action:ev.eventType,serviceId:ev.serviceId,details:historyEventDetails(ev),context:ev.reason+' • '+ev.client,status:ev.serviceStatus}));historyRowsToCsv(selected.servixEquipmentId+'-history',rows)}}><Icon name="export" size={14}/> CSV</button></div></div>
     {historyBusy?<div className="history-loading"><div className="boot-spinner"/><span>Loading equipment history…</span></div>:historyError?<div className="form-error">{historyError}</div>:<HistoryTimeline events={history}/>}
    </section>
   </div>
  </Modal>}
 {editing&&<RecordEditor kind="equipment" record={editing} onClose={()=>setEditing(null)} onSaved={async()=>{await onRefresh();setSelected(null)}}/>}
 </div>;
}
