function EquipmentView({data}:{data:DashboardData}){
 const [search,setSearch]=React.useState(''); const [coverage,setCoverage]=React.useState('All');
 const [selected,setSelected]=React.useState(null as EquipmentRecord|null); const [history,setHistory]=React.useState([] as EntityHistoryEvent[]); const [historyBusy,setHistoryBusy]=React.useState(false); const [historyError,setHistoryError]=React.useState('');
 const rows=data.equipment.filter(x=>(coverage==='All'||x.coverage===coverage)&&(x.servixEquipmentId+' '+x.client+' '+x.make+' '+x.model+' '+x.serialNumber+' '+x.type+' '+x.location).toLowerCase().includes(search.toLowerCase()));
 const relatedServices=selected?data.services.filter(s=>s.equipmentId===selected.id||(s.serialNumber&&selected.serialNumber&&s.serialNumber===selected.serialNumber)):[];
 const openEquipment=async(x:EquipmentRecord)=>{setSelected(x);setHistory([]);setHistoryError('');setHistoryBusy(true);try{setHistory(await ServixApi.getEquipmentHistory(x.id))}catch(e:any){setHistoryError(e?.message||String(e))}finally{setHistoryBusy(false)}};
 return <div className="module-content module-list-view">
  <PageHeader title="Equipment" subtitle="Client-linked equipment registry with repeat-service history and coverage context"/>
  <Toolbar><SearchBox value={search} onChange={setSearch} placeholder="Search SERVIX ID, serial, client, make or model..."/><select className="filter-select" value={coverage} onChange={e=>setCoverage(e.target.value)}><option value="All">All Coverage</option><option>Warranty</option><option>AMC</option><option>Out of Coverage</option></select></Toolbar>
  <div className="results-summary"><span><strong>{rows.length}</strong> matching equipment</span><span>Open equipment to review repeat Service Calls and its full activity timeline.</span></div>
  <section className="table-card fill-table"><div className="data-table equipment-table"><div className="tr th"><span>Equipment ID</span><span>Client</span><span>Make / Model</span><span>Serial Number</span><span>Type / Location</span><span>Coverage</span><span>History</span></div>{rows.map(x=><button className="tr record-row" key={x.id} onClick={()=>openEquipment(x)}><span><strong className="linkish">{x.servixEquipmentId}</strong></span><span><strong>{x.client}</strong></span><span><strong>{x.make||'—'}</strong><small>{x.model||'No model'}</small></span><span>{x.serialNumber||'—'}</span><span>{x.type||'—'}<small>{x.location||'No location'}</small></span><span><StatusBadge value={x.coverage}/></span><span><strong>{x.serviceCount} services</strong><small>{x.lastService?'Last: '+x.lastService:'No previous service'}</small></span></button>)}</div>{!rows.length&&<EmptyState title="No matching equipment" detail="Adjust the search or coverage filter. Equipment is normally registered during service intake."/>}</section>
  {selected&&<Modal title={(selected.make+' '+selected.model).trim()||selected.servixEquipmentId} subtitle={selected.servixEquipmentId+' • Equipment profile'} onClose={()=>setSelected(null)} wide>
   <div className="record-profile">
    <section className="profile-hero"><div><span className="eyebrow">EQUIPMENT</span><h3>{selected.make} {selected.model}</h3><p>{selected.client+' • Serial: '+(selected.serialNumber||'—')+' • '+(selected.type||'Equipment')}</p></div><StatusBadge value={selected.coverage}/></section>
    <div className="profile-metrics"><div><span>Service Calls</span><strong>{relatedServices.length}</strong></div><div><span>Open / Active</span><strong>{relatedServices.filter(s=>s.status!=='Closed').length}</strong></div><div><span>Last Service</span><strong className="metric-text">{selected.lastService||'—'}</strong></div><div><span>Location</span><strong className="metric-text">{selected.location||'—'}</strong></div></div>
    <div className="profile-grid two">
     <section className="profile-panel"><div className="panel-heading"><div><h4>Equipment Details</h4><p>Current registry information</p></div></div><div className="detail-pairs"><div><span>Client</span><strong>{selected.client}</strong></div><div><span>Make</span><strong>{selected.make||'—'}</strong></div><div><span>Model</span><strong>{selected.model||'—'}</strong></div><div><span>Serial Number</span><strong>{selected.serialNumber||'—'}</strong></div><div><span>Type</span><strong>{selected.type||'—'}</strong></div><div><span>Coverage</span><strong>{selected.coverage}</strong></div></div></section>
     <section className="profile-panel"><div className="panel-heading"><div><h4>Service Calls</h4><p>Repeat visits for this exact equipment</p></div><span className="soft-chip">{relatedServices.length}</span></div><div className="profile-list">{relatedServices.slice(0,10).map(s=><div className="profile-list-row" key={s.id}><span><strong>{s.serviceId+' • '+s.reason}</strong><small>{s.openedDate+' • '+s.complaint}</small></span><span><StatusBadge value={s.status}/><small>{s.engineer||'Unassigned'}</small></span></div>)}{!relatedServices.length&&<p className="quiet-empty">No service history yet.</p>}</div></section>
    </div>
    <section className="profile-panel entity-history-panel"><div className="panel-heading"><div><h4>Equipment Activity Timeline</h4><p>All recorded Service ID activity for this exact equipment</p></div><div className="history-actions"><span className="soft-chip">{history.length} events</span><button type="button" className="small-button history-action-button" disabled={!history.length} onClick={()=>{const rows=history.map(ev=>({dateTime:ev.createdAt,user:ev.actor,action:ev.eventType,serviceId:ev.serviceId,details:ev.note||([ev.oldValue,ev.newValue].filter(Boolean).join(' → '))||'Record activity',context:ev.reason+' • '+ev.client,status:ev.serviceStatus}));printHistoryDocument('Equipment Service History',selected.servixEquipmentId+' • '+selected.make+' '+selected.model,rows,['Client: '+selected.client,'Serial: '+(selected.serialNumber||'—'),'Coverage: '+selected.coverage+' • Service Calls: '+relatedServices.length])}}><Icon name="print" size={14}/> Print</button><button type="button" className="small-button history-action-button" disabled={!history.length} onClick={()=>{const rows=history.map(ev=>({dateTime:ev.createdAt,user:ev.actor,action:ev.eventType,serviceId:ev.serviceId,details:ev.note||([ev.oldValue,ev.newValue].filter(Boolean).join(' → '))||'Record activity',context:ev.reason+' • '+ev.client,status:ev.serviceStatus}));historyRowsToCsv(selected.servixEquipmentId+'-history',rows)}}><Icon name="export" size={14}/> CSV</button></div></div>
     {historyBusy?<div className="history-loading"><div className="boot-spinner"/><span>Loading equipment history…</span></div>:historyError?<div className="form-error">{historyError}</div>:<div className="entity-timeline">{history.map(ev=><div className="entity-timeline-row" key={ev.serviceId+'-'+ev.id}><i/><div className="entity-timeline-main"><div><strong>{ev.eventType}</strong><span className="history-service-id">{ev.serviceId}</span><small>{ev.createdAt}</small></div><p>{ev.note||([ev.oldValue,ev.newValue].filter(Boolean).join(' → '))||'Record activity'}</p><span>{ev.reason+' • '+ev.client}</span></div><div className="entity-timeline-side"><StatusBadge value={ev.serviceStatus}/><small>{ev.actor}</small></div></div>)}{!history.length&&!historyBusy&&<p className="quiet-empty">No activity events recorded yet.</p>}</div>}
    </section>
   </div>
  </Modal>}
 </div>;
}