function IntakeView({data,onRefresh,onSync}:{data:DashboardData,onRefresh:()=>void,onSync:()=>void}){
 const [tab,setTab]=React.useState('All'); const [search,setSearch]=React.useState('');
 const tabs=['All','New','Reviewed','Converted','Duplicate'];
 const rows=data.intake.filter(x=>(tab==='All'||x.status===tab)&&(`${x.client} ${x.contact} ${x.equipment} ${x.serialNumber} ${x.complaint}`.toLowerCase().includes(search.toLowerCase())));
 const change=async(id:number,status:IntakeStatus)=>{await ServixApi.updateIntakeStatus(id,status);onRefresh()};
 return <div className="module-content"><PageHeader title="Incoming Requests" subtitle="Google Form intake queue — review before creating an official Service ID" actions={<><button className="secondary-button" onClick={onSync}><Icon name="refresh"/> Sync Now</button></>}/>
  <Toolbar><SearchBox value={search} onChange={setSearch} placeholder="Search client, equipment, serial or complaint..."/><div className="tab-strip">{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t} <span>{t==='All'?data.intake.length:data.intake.filter(x=>x.status===t).length}</span></button>)}</div></Toolbar>
  <div className="results-summary"><span><strong>{rows.length}</strong> matching requests</span><span>Last sync: {data.sync.lastSuccessfulSync||'Not synced'}</span></div>
  <section className="table-card"><div className="data-table intake-table"><div className="tr th"><span>Received</span><span>Client / Contact</span><span>Equipment</span><span>Complaint / Requirement</span><span>Match</span><span>Status</span><span>Action</span></div>{rows.map(x=><div className="tr" key={x.id}><span><strong>{x.receivedAt.split(' ')[0]}</strong><small>{x.receivedAt.replace(x.receivedAt.split(' ')[0],'')}</small></span><span><strong>{x.client}</strong><small>{x.contact} • {x.mobile}</small></span><span><strong>{x.make} {x.model}</strong><small>SN: {x.serialNumber}</small></span><span className="wrap-cell">{x.complaint}</span><span><em className={`match-text ${x.matchTone}`}>{x.matchSummary}</em></span><span><StatusBadge value={x.status}/></span><span className="row-actions">{x.status==='New'&&<button className="small-button" onClick={()=>change(x.id,'Reviewed')}>Review</button>}{x.status==='Reviewed'&&<button className="small-button primary" onClick={()=>change(x.id,'Converted')}>Convert</button>}{(x.status==='Converted'||x.status==='Duplicate')&&<button className="small-button">View</button>}</span></div>)}</div>{!rows.length&&<EmptyState title="No matching requests" detail="Try another filter or sync for new Google Form submissions."/>}</section>
 </div>;
}
