const initialServiceDraft={openedDate:new Date().toISOString().slice(0,10),client:'',contact:'',mobile:'',email:'',equipment:'',make:'',model:'',serialNumber:'',reason:'Repair',complaint:'',priority:'Normal',engineer:'',serviceLocation:'Workshop',dueDate:'',status:'Open',coverage:'Out of Coverage',foc:false,quoteStatus:'No Quote',paymentStatus:'Pending'};

function ServiceCallForm({onClose,onCreated}:{onClose:()=>void,onCreated:()=>void}){
 const [draft,setDraft]=React.useState({...initialServiceDraft}); const [busy,setBusy]=React.useState(false); const [error,setError]=React.useState('');
 const set=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 const save=async()=>{if(!draft.client||!draft.equipment||!draft.reason||!draft.complaint){setError('Client, equipment, reason and complaint are required.');return;} setBusy(true);setError('');try{await ServixApi.createServiceCall(draft);onCreated();onClose()}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 return <Modal title="New Service Call" subtitle="Fast intake with secondary details revealed only when needed" onClose={onClose} wide footer={<><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy} onClick={save}>{busy?'Saving...':'Save Service Call'}</button></>}>
  {error&&<div className="form-error">{error}</div>}
  <div className="form-section"><div className="section-number">1</div><div className="form-section-body"><div className="section-title"><h3>Client & Equipment</h3><p>Select existing records or enter the service intake information.</p></div><div className="form-grid four"><Field label="Client Name" required wide><input value={draft.client} onChange={e=>set('client',e.target.value)} placeholder="Search or type client"/></Field><Field label="Contact Person"><input value={draft.contact} onChange={e=>set('contact',e.target.value)}/></Field><Field label="Mobile"><input value={draft.mobile} onChange={e=>set('mobile',e.target.value)}/></Field><Field label="Email"><input value={draft.email} onChange={e=>set('email',e.target.value)} type="email"/></Field><Field label="Equipment" required wide><input value={draft.equipment} onChange={e=>set('equipment',e.target.value)} placeholder="e.g. Audiometer"/></Field><Field label="Make"><input value={draft.make} onChange={e=>set('make',e.target.value)}/></Field><Field label="Model"><input value={draft.model} onChange={e=>set('model',e.target.value)}/></Field><Field label="Serial Number"><input value={draft.serialNumber} onChange={e=>set('serialNumber',e.target.value)}/></Field></div></div></div>
  <div className="form-section"><div className="section-number">2</div><div className="form-section-body"><div className="section-title"><h3>Service Details</h3><p>Only the operational information needed to start the call.</p></div><div className="form-grid four"><Field label="Opened Date" required><input type="date" value={draft.openedDate} onChange={e=>set('openedDate',e.target.value)}/></Field><Field label="Reason" required><select value={draft.reason} onChange={e=>set('reason',e.target.value)}><option>Repair</option><option>Calibration</option><option>Preventive Service</option><option>Installation / Commissioning</option><option>Inspection</option><option>Other</option></select></Field><Field label="Priority"><select value={draft.priority} onChange={e=>set('priority',e.target.value)}><option>Normal</option><option>Urgent</option><option>High</option><option>Low</option></select></Field><Field label="Status"><select value={draft.status} onChange={e=>set('status',e.target.value)}><option>Open</option><option>In Progress</option><option>Pending</option><option>Closed</option></select></Field><Field label="Complaint / Requirement" required wide><textarea value={draft.complaint} onChange={e=>set('complaint',e.target.value)} placeholder="Describe the issue reported by the client"/></Field><Field label="Assigned Engineer"><input value={draft.engineer} onChange={e=>set('engineer',e.target.value)} placeholder="Select engineer"/></Field><Field label="Service Location"><select value={draft.serviceLocation} onChange={e=>set('serviceLocation',e.target.value)}><option>Workshop</option><option>Onsite</option><option>Other</option></select></Field><Field label="Due Date"><input type="date" value={draft.dueDate} onChange={e=>set('dueDate',e.target.value)}/></Field></div></div></div>
  <div className="form-section"><div className="section-number">3</div><div className="form-section-body"><div className="section-title"><h3>Coverage / Commercial</h3><p>Compact controls keep the form simple.</p></div><div className="choice-group"><div><span className="choice-label">Coverage</span>{['Warranty','AMC','Out of Coverage'].map(v=><button type="button" className={draft.coverage===v?'selected':''} onClick={()=>set('coverage',v)} key={v}>{v}</button>)}</div><div><span className="choice-label">FOC</span>{[true,false].map(v=><button type="button" className={draft.foc===v?'selected':''} onClick={()=>set('foc',v)} key={String(v)}>{v?'Yes':'No'}</button>)}</div><div><span className="choice-label">Quote</span>{['Quote Sent','No Quote','Phone Discussed'].map(v=><button type="button" className={draft.quoteStatus===v?'selected':''} onClick={()=>set('quoteStatus',v)} key={v}>{v}</button>)}</div><div><span className="choice-label">Payment</span>{['Pending','Paid'].map(v=><button type="button" className={draft.paymentStatus===v?'selected':''} onClick={()=>set('paymentStatus',v)} key={v}>{v}</button>)}</div></div></div></div>
 </Modal>;
}

function ServiceDetailModal({service,onClose,onUpdated}:{service:ServiceCall,onClose:()=>void,onUpdated:()=>void}){
 const [detail,setDetail]=React.useState(null as ServiceDetail|null); const [draft,setDraft]=React.useState(null as any); const [tab,setTab]=React.useState('Service'); const [busy,setBusy]=React.useState(false); const [error,setError]=React.useState(''); const [note,setNote]=React.useState(''); const [showPart,setShowPart]=React.useState(false); const [part,setPart]=React.useState({itemName:'',make:'',model:'',partNumber:'',quantity:1,remarks:''});
 const toDraft=(d:ServiceDetail)=>({id:d.id,reason:d.reason,complaint:d.complaint,engineer:d.engineer,status:d.status,priority:d.priority,serviceLocation:d.serviceLocation,dueDate:d.dueDate,coverage:d.coverage,foc:d.foc,quoteStatus:d.quoteStatus,paymentStatus:d.paymentStatus,diagnosis:d.diagnosis,workPerformed:d.workPerformed,testingVerification:d.testingVerification,finalResult:d.finalResult,recommendations:d.recommendations,receivedCondition:d.receivedCondition,receivedAccessories:d.receivedAccessories,receivedRemarks:d.receivedRemarks,completionDate:d.completionDate});
 React.useEffect(()=>{ServixApi.getServiceDetail(service.id).then(d=>{setDetail(d);setDraft(toDraft(d))}).catch(e=>setError(e?.message||String(e)))},[service.id]);
 const set=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 const save=async()=>{if(!draft)return;setBusy(true);setError('');try{const d=await ServixApi.updateServiceDetail(draft);setDetail(d);setDraft(toDraft(d));await onUpdated()}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 const addNote=async()=>{if(!note.trim())return;setBusy(true);setError('');try{const d=await ServixApi.addServiceNote(service.id,note);setDetail(d);setDraft(toDraft(d));setNote('');setTab('History')}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 const addPart=async()=>{if(!part.itemName.trim())return;setBusy(true);setError('');try{const d=await ServixApi.addServicePart({serviceCallId:service.id,...part,quantity:Number(part.quantity)||1});setDetail(d);setDraft(toDraft(d));setPart({itemName:'',make:'',model:'',partNumber:'',quantity:1,remarks:''});setShowPart(false);await onUpdated()}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 const tabs=['Service','Received Item','Parts Used','History'];
 return <Modal title={detail?detail.serviceId:service.serviceId} subtitle="Service workspace — edit the call, record work and retain the complete history" onClose={onClose} wide footer={<><button className="secondary-button" onClick={onClose}>Close</button>{draft&&<button className="primary-button" disabled={busy} onClick={save}>{busy?'Saving...':'Save Changes'}</button>}</>}>
  {error&&<div className="form-error">{error}</div>}
  {!detail||!draft?<div className="detail-loading"><div className="boot-spinner"/><span>Loading service record…</span></div>:<>
   <div className="detail-hero"><div><div className="detail-title-line"><strong>{detail.client}</strong><StatusBadge value={draft.status}/></div><p>{detail.equipment}{detail.make||detail.model?` • ${detail.make} ${detail.model}`:''}{detail.serialNumber?` • S/N ${detail.serialNumber}`:''}</p></div><div className="detail-meta"><span><small>Opened</small><strong>{detail.openedDate}</strong></span><span><small>Reason</small><strong>{draft.reason}</strong></span><span><small>Engineer</small><strong>{draft.engineer||'Unassigned'}</strong></span><span><small>Updated</small><strong>{detail.updatedAt}</strong></span></div></div>
   <div className="detail-tabs">{tabs.map(t=><button type="button" key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}{t==='Parts Used'&&detail.parts.length>0?<b>{detail.parts.length}</b>:null}{t==='History'&&detail.events.length>0?<b>{detail.events.length}</b>:null}</button>)}</div>
   {tab==='Service'&&<div className="detail-panel-grid"><section className="detail-card"><div className="detail-card-head"><div><h3>Operational Details</h3><p>Keep status and responsibility current.</p></div></div><div className="form-grid four"><Field label="Status"><select value={draft.status} onChange={e=>set('status',e.target.value)}><option>Open</option><option>In Progress</option><option>Pending</option><option>Closed</option></select></Field><Field label="Priority"><select value={draft.priority} onChange={e=>set('priority',e.target.value)}><option>Normal</option><option>Urgent</option><option>High</option><option>Low</option></select></Field><Field label="Engineer"><input value={draft.engineer} onChange={e=>set('engineer',e.target.value)}/></Field><Field label="Due Date"><input type="date" value={draft.dueDate||''} onChange={e=>set('dueDate',e.target.value)}/></Field><Field label="Reason"><select value={draft.reason} onChange={e=>set('reason',e.target.value)}><option>Repair</option><option>Calibration</option><option>Preventive Service</option><option>Installation / Commissioning</option><option>Inspection</option><option>Other</option></select></Field><Field label="Service Location"><select value={draft.serviceLocation} onChange={e=>set('serviceLocation',e.target.value)}><option>Workshop</option><option>Onsite</option><option>Other</option></select></Field><Field label="Complaint / Requirement" wide><textarea value={draft.complaint} onChange={e=>set('complaint',e.target.value)}/></Field></div></section>
    <section className="detail-card"><div className="detail-card-head"><div><h3>Inspection & Work</h3><p>Technical work remains readable and report-ready.</p></div></div><div className="detail-text-grid"><Field label="Diagnosis"><textarea value={draft.diagnosis} onChange={e=>set('diagnosis',e.target.value)} placeholder="Inspection findings / diagnosis"/></Field><Field label="Work Performed"><textarea value={draft.workPerformed} onChange={e=>set('workPerformed',e.target.value)} placeholder="Work completed during this service"/></Field><Field label="Testing / Verification"><textarea value={draft.testingVerification} onChange={e=>set('testingVerification',e.target.value)} placeholder="Testing and verification after work"/></Field><Field label="Final Result"><textarea value={draft.finalResult} onChange={e=>set('finalResult',e.target.value)} placeholder="Final service outcome"/></Field><Field label="Recommendations / Follow-up"><textarea value={draft.recommendations} onChange={e=>set('recommendations',e.target.value)} placeholder="Recommendations or next action"/></Field><Field label="Completion Date"><input type="date" value={draft.completionDate||''} onChange={e=>set('completionDate',e.target.value)}/></Field></div></section>
    <section className="detail-card detail-commercial"><div className="detail-card-head"><div><h3>Coverage & Commercial</h3><p>Compact status only — SERVIX is not accounting software.</p></div></div><div className="choice-stack"><label><span>Coverage</span><div>{['Warranty','AMC','Out of Coverage'].map(v=><button type="button" className={draft.coverage===v?'selected':''} onClick={()=>set('coverage',v)} key={v}>{v}</button>)}</div></label><label><span>FOC</span><div>{[true,false].map(v=><button type="button" className={draft.foc===v?'selected':''} onClick={()=>set('foc',v)} key={String(v)}>{v?'Yes':'No'}</button>)}</div></label><label><span>Quote</span><div>{['Quote Sent','No Quote','Phone Discussed'].map(v=><button type="button" className={draft.quoteStatus===v?'selected':''} onClick={()=>set('quoteStatus',v)} key={v}>{v}</button>)}</div></label><label><span>Payment</span><div>{['Pending','Paid'].map(v=><button type="button" className={draft.paymentStatus===v?'selected':''} onClick={()=>set('paymentStatus',v)} key={v}>{v}</button>)}</div></label></div></section>
   </div>}
   {tab==='Received Item'&&<div className="detail-panel-grid received-grid"><section className="detail-card"><div className="detail-card-head"><div><h3>Condition When Received</h3><p>Quick evidence without turning intake into a long form.</p></div></div><div className="condition-choice">{['Good','Used','Damaged','Not Working'].map(v=><button type="button" className={draft.receivedCondition===v?'selected':''} onClick={()=>set('receivedCondition',v)} key={v}>{v}</button>)}</div><div className="detail-text-grid received-fields"><Field label="Accessories / Items Received"><textarea value={draft.receivedAccessories} onChange={e=>set('receivedAccessories',e.target.value)} placeholder="Power adapter, probe, carry case…"/></Field><Field label="Condition Remarks"><textarea value={draft.receivedRemarks} onChange={e=>set('receivedRemarks',e.target.value)} placeholder="Scratches, broken or missing items, packaging condition…"/></Field></div></section><section className="detail-card evidence-card"><div className="feature-icon"><Icon name="documents" size={24}/></div><div><h3>Photos & Documents</h3><p>{detail.attachmentCount?`${detail.attachmentCount} linked file(s)`:'No files linked yet'}</p><small>Client Letter • DC • Condition Photo • Service Report • Certificate</small></div><button type="button" className="secondary-button" disabled>Add files in next document step</button></section></div>}
   {tab==='Parts Used'&&<div className="detail-card"><div className="detail-card-head"><div><h3>Parts / Items Used</h3><p>Consumption history only — no warehouse stock management.</p></div><button className="secondary-button" onClick={()=>setShowPart(!showPart)}><Icon name="plus"/> Add Item</button></div>{showPart&&<div className="part-entry"><div className="form-grid four"><Field label="Part / Item" required wide><input value={part.itemName} onChange={e=>setPart({...part,itemName:e.target.value})}/></Field><Field label="Make"><input value={part.make} onChange={e=>setPart({...part,make:e.target.value})}/></Field><Field label="Model"><input value={part.model} onChange={e=>setPart({...part,model:e.target.value})}/></Field><Field label="Part Number"><input value={part.partNumber} onChange={e=>setPart({...part,partNumber:e.target.value})}/></Field><Field label="Quantity"><input type="number" min="1" value={part.quantity} onChange={e=>setPart({...part,quantity:Number(e.target.value)})}/></Field><Field label="Remarks" wide><input value={part.remarks} onChange={e=>setPart({...part,remarks:e.target.value})}/></Field></div><div className="part-entry-actions"><button className="text-button" onClick={()=>setShowPart(false)}>Cancel</button><button className="primary-button" disabled={busy} onClick={addPart}>Add to Service</button></div></div>}<div className="parts-detail-list">{detail.parts.map(p=><div className="part-detail-row" key={p.id}><span className="part-qty">{p.quantity}</span><span><strong>{p.itemName}</strong><small>{[p.make,p.model,p.partNumber].filter(Boolean).join(' • ')||'No reference details'}</small></span><span><small>{p.usedAt}</small><strong>{p.remarks||'—'}</strong></span></div>)}{!detail.parts.length&&<EmptyState title="No parts recorded" detail="Add only items actually used during this service."/>}</div></div>}
   {tab==='History'&&<div className="history-layout"><section className="detail-card note-card"><h3>Add Service Note</h3><p>Free-form notes remain part of this Service ID history.</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add an update, follow-up note or communication summary…"/><button className="primary-button" disabled={busy||!note.trim()} onClick={addNote}>Add Note</button></section><section className="detail-card history-card"><div className="detail-card-head"><div><h3>Complete Activity</h3><p>Newest activity first.</p></div><span className="soft-chip">{detail.events.length} events</span></div><div className="timeline">{detail.events.map(ev=><div className="timeline-row" key={ev.id}><i/><div><div><strong>{ev.eventType}</strong><small>{ev.createdAt}</small></div><p>{ev.note||([ev.oldValue,ev.newValue].filter(Boolean).join(' → '))||'Record activity'}</p><span>{ev.actor}</span></div></div>)}</div></section></div>}
  </>}
 </Modal>;
}

function ServiceCallsView({data,onRefresh}:{data:DashboardData,onRefresh:()=>void}){
 const [search,setSearch]=React.useState(''); const [status,setStatus]=React.useState('All'); const [reason,setReason]=React.useState('All'); const [coverage,setCoverage]=React.useState('All'); const [showNew,setShowNew]=React.useState(false); const [selectedService,setSelectedService]=React.useState(null as ServiceCall|null); const [selected,setSelected]=React.useState([] as number[]);
 const rows=data.services.filter(x=>(status==='All'||x.status===status)&&(reason==='All'||x.reason===reason)&&(coverage==='All'||x.coverage===coverage)&&(`${x.serviceId} ${x.client} ${x.equipment} ${x.reason} ${x.engineer} ${x.serialNumber||''}`.toLowerCase().includes(search.toLowerCase())));
 const allVisibleSelected=rows.length>0&&rows.every(r=>selected.includes(r.id));
 const toggleAll=()=>setSelected(allVisibleSelected?selected.filter(id=>!rows.some(r=>r.id===id)):Array.from(new Set([...selected,...rows.map(r=>r.id)])));
 const toggleOne=(id:number)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 return <div className="module-content"><PageHeader title="Service Calls" subtitle="Create, track and close service requests while retaining the full history" actions={<button className="primary-button" onClick={()=>setShowNew(true)}><Icon name="plus"/> New Service Call</button>}/>
  <Toolbar><SearchBox value={search} onChange={setSearch} placeholder="Search Service ID, client, equipment, serial, reason..."/><select className="filter-select" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Open</option><option>In Progress</option><option>Pending</option><option>Closed</option></select><select className="filter-select" value={reason} onChange={e=>setReason(e.target.value)}><option>All</option><option>Repair</option><option>Calibration</option><option>Preventive Service</option><option>Installation / Commissioning</option><option>Inspection</option><option>Other</option></select><select className="filter-select" value={coverage} onChange={e=>setCoverage(e.target.value)}><option>All</option><option>Warranty</option><option>AMC</option><option>Out of Coverage</option></select><button className="text-button" onClick={()=>{setSearch('');setStatus('All');setReason('All');setCoverage('All')}}>Clear All</button><button className="secondary-button"><Icon name="export"/> Export</button></Toolbar>
  <div className="results-summary"><span><strong>{rows.length}</strong> matching service calls {selected.length>0&&<>• <strong>{selected.length}</strong> selected</>}</span><span>Open a Service ID to work on the complete record.</span></div>
  <section className="table-card"><div className="data-table service-table"><div className="tr th"><span><input type="checkbox" checked={allVisibleSelected} onChange={toggleAll}/></span><span>Service ID</span><span>Opened</span><span>Client</span><span>Equipment</span><span>Reason</span><span>Engineer</span><span>Status</span><span>Coverage</span><span>Payment</span></div>{rows.map(x=><div className="tr" key={x.id}><span><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggleOne(x.id)}/></span><span><button className="service-link" onClick={()=>setSelectedService(x)}>{x.serviceId}</button></span><span>{x.openedDate}</span><span><strong>{x.client}</strong></span><span><strong>{x.equipment}</strong><small>{x.make} {x.model} {x.serialNumber&&`• ${x.serialNumber}`}</small></span><span>{x.reason}</span><span>{x.engineer||'—'}</span><span><StatusBadge value={x.status}/></span><span>{x.coverage}{x.foc&&<small> • FOC</small>}</span><span><StatusBadge value={x.paymentStatus}/></span></div>)}</div>{!rows.length&&<EmptyState title="No matching service calls" detail="Adjust the filters or create a new service call."/>}</section>
  {showNew&&<ServiceCallForm onClose={()=>setShowNew(false)} onCreated={onRefresh}/>} {selectedService&&<ServiceDetailModal service={selectedService} onClose={()=>setSelectedService(null)} onUpdated={onRefresh}/>}</div>;
}
