const initialServiceDraft={openedDate:new Date().toISOString().slice(0,10),client:'',contact:'',mobile:'',email:'',equipment:'',make:'',model:'',serialNumber:'',reason:'Repair',complaint:'',priority:'Normal',engineer:'',serviceLocation:'Workshop',dueDate:'',status:'Open',coverage:'Out of Coverage',foc:false,quoteStatus:'No Quote',paymentStatus:'Pending'};

function ServiceCallForm({onClose,onCreated,initialDraft}:{onClose:()=>void,onCreated:()=>void,initialDraft?:any}){
 const [draft,setDraft]=React.useState({...initialServiceDraft,...(initialDraft||{})}); const [busy,setBusy]=React.useState(false); const [error,setError]=React.useState('');
 const [review,setReview]=React.useState(null as DuplicateReview|null); const [clientChoice,setClientChoice]=React.useState(''); const [equipmentChoice,setEquipmentChoice]=React.useState(''); const [overridePassword,setOverridePassword]=React.useState(''); const [reviewError,setReviewError]=React.useState('');
 const set=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 const finishCreate=async(payload:any)=>{setBusy(true);setError('');setReviewError('');try{await ServixApi.createServiceCall(payload);await onCreated();onClose()}catch(e:any){const msg=e?.message||String(e);if(review)setReviewError(msg);else setError(msg)}finally{setBusy(false)}};
 const save=async()=>{if(!draft.client||!draft.equipment||!draft.reason||!draft.complaint){setError('Client, equipment, reason and complaint are required.');return;}setBusy(true);setError('');try{const result=await ServixApi.reviewServiceDuplicates(draft);if(result.level==='clear'){await finishCreate(draft);return;}setReview(result);setClientChoice(result.clientCandidates.length===1?'client:'+result.clientCandidates[0].id:(result.clientCandidates.length?'':'new'));const clientId=result.clientCandidates.length===1?result.clientCandidates[0].id:null;const exactClientEquipment=result.equipmentCandidates.filter(e=>clientId&&e.clientId===clientId&&draft.serialNumber&&e.serialNumber.toLowerCase()===String(draft.serialNumber).trim().toLowerCase());setEquipmentChoice(exactClientEquipment.length===1?'equipment:'+exactClientEquipment[0].id:(result.equipmentCandidates.length?'':'new'));setOverridePassword('');setReviewError('')}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 const chooseEquipment=(value:string)=>{setEquipmentChoice(value);if(value.startsWith('equipment:')){const id=Number(value.split(':')[1]);const eq=review?.equipmentCandidates.find(x=>x.id===id);if(eq)setClientChoice('client:'+eq.clientId)}};
 const confirmCreate=async()=>{if(!review)return;if(review.clientCandidates.length&&!clientChoice){setReviewError('Choose the client record SERVIX should use, or choose Create Separate Client.');return}if(review.equipmentCandidates.length&&!equipmentChoice){setReviewError('Choose the equipment record SERVIX should use, or choose Create Separate Equipment.');return}let selectedClientId=clientChoice.startsWith('client:')?Number(clientChoice.split(':')[1]):null;const selectedEquipmentId=equipmentChoice.startsWith('equipment:')?Number(equipmentChoice.split(':')[1]):null;if(selectedEquipmentId){const eq=review.equipmentCandidates.find(x=>x.id===selectedEquipmentId);if(eq)selectedClientId=eq.clientId}const forceNewClient=clientChoice==='new'&&review.clientCandidates.length>0;const forceNewEquipment=equipmentChoice==='new'&&review.equipmentCandidates.length>0;const needsPassword=review.requiresOverride||forceNewClient||forceNewEquipment;if(needsPassword&&!overridePassword){setReviewError('Enter an Administrator password to approve this duplicate/conflict override.');return}await finishCreate({...draft,selectedClientId,selectedEquipmentId,forceNewClient,forceNewEquipment,duplicateOverridePassword:needsPassword?overridePassword:''})};
 if(review){
  const forceNewClient=clientChoice==='new'&&review.clientCandidates.length>0;const forceNewEquipment=equipmentChoice==='new'&&review.equipmentCandidates.length>0;const needsPassword=review.requiresOverride||forceNewClient||forceNewEquipment;
  return <Modal title={review.level==='warning'?'Duplicate / Conflict Review':'Existing Record Found'} subtitle="Confirm exactly which Client and Equipment SERVIX should link before the Service ID is created" onClose={()=>setReview(null)} wide footer={<><button className="secondary-button" disabled={busy} onClick={()=>{setReview(null);setReviewError('')}}>Back to Form</button><button className="primary-button" disabled={busy} onClick={confirmCreate}>{busy?'Creating...':needsPassword?'Override & Create Service Call':'Confirm & Create Service Call'}</button></>}>
   <div className={'duplicate-summary '+review.level}><Icon name={review.level==='warning'?'bell':'shield'} size={22}/><div><strong>{review.summary}</strong><p>No existing Client or Equipment record will be silently overwritten from this Service Call form.</p></div></div>
   {review.warnings.length>0&&<div className="duplicate-warning-list">{review.warnings.map((w,i)=><div key={i}><Icon name="bell" size={16}/><span>{w}</span></div>)}</div>}
   <div className="duplicate-review-grid">
    <section className="duplicate-review-card"><h3>Client Match</h3><p>{review.clientCandidates.length?(review.clientCandidates.length+' existing client record(s) match the entered mobile/email.'):'No client match found — a new client will be created.'}</p>
     {review.clientCandidates.length>0&&<Field label="Use Client Record" required><select value={clientChoice} onChange={e=>setClientChoice(e.target.value)}><option value="">Choose client…</option>{review.clientCandidates.map(c=><option key={c.id} value={'client:'+c.id}>{c.code+' — '+c.name+' — '+(c.mobile||c.email)}</option>)}<option value="new">Create Separate Client</option></select></Field>}
     <div className="duplicate-candidates">{review.clientCandidates.map(c=><div className={'duplicate-candidate '+(clientChoice==='client:'+c.id?'selected':'')} key={c.id}><strong>{c.code+' • '+c.name}</strong><span>{(c.contact||'No contact')+' • '+(c.mobile||'No mobile')}</span><small>{c.serviceCount+' services • '+c.equipmentCount+' equipment'}</small></div>)}</div>
    </section>
    <section className="duplicate-review-card"><h3>Equipment / Repeat Visit</h3><p>{review.equipmentCandidates.length?(draft.serialNumber?review.equipmentCandidates.length+' possible equipment record(s) found for this client / serial. Select the returning device if it already exists.':review.equipmentCandidates.length+' registered device(s) already belong to this client. Select the returning device or create a new one.'):'No existing equipment match found — a new equipment record will be created.'}</p>
     {review.equipmentCandidates.length>0&&<Field label="Use Equipment Record" required><select value={equipmentChoice} onChange={e=>chooseEquipment(e.target.value)}><option value="">Choose equipment…</option>{review.equipmentCandidates.map(e=><option key={e.id} value={'equipment:'+e.id}>{e.servixEquipmentId+' — '+e.clientName+' — '+e.make+' '+e.model}</option>)}<option value="new">Create Separate Equipment</option></select></Field>}
     <div className="duplicate-candidates">{review.equipmentCandidates.map(e=><div className={'duplicate-candidate '+(equipmentChoice==='equipment:'+e.id?'selected':'')} key={e.id}><strong>{e.servixEquipmentId+' • '+e.make+' '+e.model}</strong><span>{e.clientName+' • S/N '+e.serialNumber}</span><small>{e.serviceCount+' previous service call(s)'}</small></div>)}</div>
    </section>
   </div>
   {review.openServices.length>0&&<section className="duplicate-open-services"><div><h3>Existing Open Service Calls</h3><p>Review these before creating another open job for the same equipment.</p></div>{review.openServices.map(s=><div className="duplicate-open-row" key={s.id}><span><strong>{s.serviceId}</strong><small>{s.openedDate+' • '+s.client+' • '+s.equipment}</small></span><span className="wrap-cell">{s.complaint}</span><StatusBadge value={s.status}/></div>)}</section>}
   {needsPassword&&<div className="duplicate-override"><div><strong>Administrator Override Required</strong><p>The password is verified locally and is never stored in the Service Call or history.</p></div><Field label="Administrator Password" required><input type="password" value={overridePassword} onChange={e=>setOverridePassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&confirmCreate()} placeholder="Enter administrator password"/></Field></div>}
   {reviewError&&<div className="form-error">{reviewError}</div>}
  </Modal>
 }
 return <Modal title="New Service Call" subtitle={draft.sourceIntakeId?'Converted from reviewed incoming request — Service ID is created only after save':'Fast intake with secondary details revealed only when needed'} onClose={onClose} wide footer={<><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy} onClick={save}>{busy?'Checking...':'Review & Save Service Call'}</button></>}>
  {error&&<div className="form-error">{error}</div>}
  <div className="form-section"><div className="section-number">1</div><div className="form-section-body"><div className="section-title"><h3>Client & Equipment</h3><p>SERVIX checks mobile/email and serial history before creating the Service ID.</p></div><div className="form-grid four"><Field label="Client Name" required wide><input value={draft.client} onChange={e=>set('client',e.target.value)} placeholder="Search or type client"/></Field><Field label="Contact Person"><input value={draft.contact} onChange={e=>set('contact',e.target.value)}/></Field><Field label="Mobile"><input value={draft.mobile} onChange={e=>set('mobile',e.target.value)}/></Field><Field label="Email"><input value={draft.email} onChange={e=>set('email',e.target.value)} type="email"/></Field><Field label="Equipment" required wide><input value={draft.equipment} onChange={e=>set('equipment',e.target.value)} placeholder="e.g. Audiometer"/></Field><Field label="Make"><input value={draft.make} onChange={e=>set('make',e.target.value)}/></Field><Field label="Model"><input value={draft.model} onChange={e=>set('model',e.target.value)}/></Field><Field label="Serial Number"><input value={draft.serialNumber} onChange={e=>set('serialNumber',e.target.value)}/></Field></div></div></div>
  <div className="form-section"><div className="section-number">2</div><div className="form-section-body"><div className="section-title"><h3>Service Details</h3><p>Only the operational information needed to start the call.</p></div><div className="form-grid four"><Field label="Opened Date" required><input type="date" value={draft.openedDate} onChange={e=>set('openedDate',e.target.value)}/></Field><Field label="Reason" required><select value={draft.reason} onChange={e=>set('reason',e.target.value)}><option>Repair</option><option>Calibration</option><option>Preventive Service</option><option>Installation / Commissioning</option><option>Inspection</option><option>Other</option></select></Field><Field label="Priority"><select value={draft.priority} onChange={e=>set('priority',e.target.value)}><option>Normal</option><option>Urgent</option><option>High</option><option>Low</option></select></Field><Field label="Status"><select value={draft.status} onChange={e=>set('status',e.target.value)}><option>Open</option><option>In Progress</option><option>Pending</option><option>Closed</option></select></Field><Field label="Complaint / Requirement" required wide><textarea value={draft.complaint} onChange={e=>set('complaint',e.target.value)} placeholder="Describe the issue reported by the client"/></Field><Field label="Assigned Engineer"><input value={draft.engineer} onChange={e=>set('engineer',e.target.value)} placeholder="Select engineer"/></Field><Field label="Service Location"><select value={draft.serviceLocation} onChange={e=>set('serviceLocation',e.target.value)}><option>Workshop</option><option>Onsite</option><option>Other</option></select></Field><Field label="Due Date"><input type="date" value={draft.dueDate} onChange={e=>set('dueDate',e.target.value)}/></Field></div></div></div>
  <div className="form-section"><div className="section-number">3</div><div className="form-section-body"><div className="section-title"><h3>Coverage / Commercial</h3><p>Compact controls keep the form simple.</p></div><div className="choice-group"><div><span className="choice-label">Coverage</span>{['Warranty','AMC','Out of Coverage'].map(v=><button type="button" className={draft.coverage===v?'selected':''} onClick={()=>set('coverage',v)} key={v}>{v}</button>)}</div><div><span className="choice-label">FOC</span>{[true,false].map(v=><button type="button" className={draft.foc===v?'selected':''} onClick={()=>set('foc',v)} key={String(v)}>{v?'Yes':'No'}</button>)}</div><div><span className="choice-label">Quote</span>{['Quote Sent','No Quote'].map(v=><button type="button" className={draft.quoteStatus===v?'selected':''} onClick={()=>set('quoteStatus',v)} key={v}>{v}</button>)}</div><div><span className="choice-label">Payment</span>{['Pending','Paid'].map(v=><button type="button" className={draft.paymentStatus===v?'selected':''} onClick={()=>set('paymentStatus',v)} key={v}>{v}</button>)}</div></div></div></div>
 </Modal>
}

function ServiceDetailModal({service,onClose,onUpdated}:{service:ServiceCall,onClose:()=>void,onUpdated:()=>void}){
 const [detail,setDetail]=React.useState(null as ServiceDetail|null); const [draft,setDraft]=React.useState(null as any); const [tab,setTab]=React.useState('Service'); const [busy,setBusy]=React.useState(false); const [error,setError]=React.useState(''); const [note,setNote]=React.useState(''); const [showPart,setShowPart]=React.useState(false); const [part,setPart]=React.useState({itemName:'',make:'',model:'',partNumber:'',quantity:1,remarks:''});
 const toDraft=(d:ServiceDetail)=>({id:d.id,reason:d.reason,complaint:d.complaint,engineer:d.engineer,status:d.status,priority:d.priority,serviceLocation:d.serviceLocation,dueDate:d.dueDate,coverage:d.coverage,foc:d.foc,quoteStatus:d.quoteStatus,paymentStatus:d.paymentStatus,diagnosis:d.diagnosis,workPerformed:d.workPerformed,testingVerification:d.testingVerification,finalResult:d.finalResult,recommendations:d.recommendations,receivedCondition:d.receivedCondition,receivedAccessories:d.receivedAccessories,receivedRemarks:d.receivedRemarks,completionDate:d.completionDate});
 React.useEffect(()=>{ServixApi.getServiceDetail(service.id).then(d=>{setDetail(d);setDraft(toDraft(d))}).catch(e=>setError(e?.message||String(e)))},[service.id]);
 const set=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 const save=async()=>{if(!draft)return;setBusy(true);setError('');try{const d=await ServixApi.updateServiceDetail(draft);setDetail(d);setDraft(toDraft(d));await onUpdated()}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 const addNote=async()=>{if(!note.trim())return;setBusy(true);setError('');try{const d=await ServixApi.addServiceNote(service.id,note);setDetail(d);setDraft(toDraft(d));setNote('');setTab('Notes')}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 const addPart=async()=>{if(!part.itemName.trim())return;setBusy(true);setError('');try{const d=await ServixApi.addServicePart({serviceCallId:service.id,...part,quantity:Number(part.quantity)||1});setDetail(d);setDraft(toDraft(d));setPart({itemName:'',make:'',model:'',partNumber:'',quantity:1,remarks:''});setShowPart(false);await onUpdated()}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 const tabs=[{key:'Service',icon:'service'},{key:'Received Item',icon:'intake'},{key:'Parts Used',icon:'parts'},{key:'Notes',icon:'service'},{key:'History',icon:'reports'}];
 const hasUnsaved=!!detail&&!!draft&&JSON.stringify(toDraft(detail))!==JSON.stringify(draft);
 const dueOverdue=!!draft?.dueDate&&draft.status!=='Closed'&&draft.dueDate<new Date().toISOString().slice(0,10);
 return <Modal title="Service Workspace" subtitle={(detail?detail.serviceId:service.serviceId)+' • open, update and retain the complete Service ID history'} onClose={onClose} wide className="service-workspace-modal" footer={<><button className="secondary-button" onClick={onClose}>Close</button>{draft&&<button className="primary-button" disabled={busy||!hasUnsaved} onClick={save}>{busy?'Saving...':hasUnsaved?'Save Changes':'Saved'}</button>}</>}>
  {error&&<div className="form-error">{error}</div>}
  {!detail||!draft?<div className="detail-loading"><div className="boot-spinner"/><span>Loading service record…</span></div>:<>
   <div className="service-workspace-head">
    <div className="service-workspace-id"><span className="service-workspace-icon"><Icon name="service" size={22}/></span><span><small>SERVICE ID</small><strong>{detail.serviceId}</strong><em>Click controls below to update this job</em></span></div>
    <div className="service-workspace-record"><div className="detail-title-line"><strong>{detail.client}</strong><StatusBadge value={draft.status}/></div><p>{detail.equipment}{detail.make||detail.model?` • ${detail.make} ${detail.model}`:''}{detail.serialNumber?` • S/N ${detail.serialNumber}`:''}</p></div>
    <div className="service-workspace-meta"><span><small>Opened</small><strong>{detail.openedDate}</strong></span><span><small>Reason</small><strong>{draft.reason}</strong></span><span><small>Updated</small><strong>{detail.updatedAt}</strong></span></div>
   </div>
   <section className="service-control-panel">
    <div className="service-control-heading"><div><strong>Service Controls</strong><span>Status, responsibility and commercial tags for this Service ID.</span></div>{hasUnsaved&&<span className="unsaved-chip"><i/> Changes not saved</span>}</div>
    <div className="service-control-grid">
     <label className={'service-control-chip control-status '+(draft.status==='Closed'?'tone-green':draft.status==='Pending'?'tone-amber':'tone-blue')}><span className="service-control-icon"><Icon name="status" size={18}/></span><span><small>Status</small><select value={draft.status} onChange={e=>set('status',e.target.value)}><option>Open</option><option>In Progress</option><option>Pending</option><option>Closed</option></select></span></label>
     <label className={'service-control-chip control-payment '+(draft.paymentStatus==='Paid'?'tone-green':'tone-amber')}><span className="service-control-icon"><Icon name="payment" size={18}/></span><span><small>Payment</small><select value={draft.paymentStatus} onChange={e=>set('paymentStatus',e.target.value)}><option>Pending</option><option>Paid</option></select></span></label>
     <label className={'service-control-chip control-quote '+(draft.quoteStatus==='Quote Sent'?'tone-blue':'tone-slate')}><span className="service-control-icon"><Icon name="quote" size={18}/></span><span><small>Quote</small><select value={draft.quoteStatus} onChange={e=>set('quoteStatus',e.target.value)}><option>Quote Sent</option><option>No Quote</option></select></span></label>
     <label className={'service-control-chip control-coverage '+(draft.coverage==='Warranty'?'tone-blue':draft.coverage==='AMC'?'tone-green':'tone-amber')}><span className="service-control-icon"><Icon name="shield" size={18}/></span><span><small>Coverage</small><select value={draft.coverage} onChange={e=>set('coverage',e.target.value)}><option>Warranty</option><option>AMC</option><option>Out of Coverage</option></select></span></label>
     <label className={'service-control-chip control-priority '+(draft.priority==='Urgent'||draft.priority==='High'?'tone-red':'tone-slate')}><span className="service-control-icon"><Icon name="flag" size={18}/></span><span><small>Priority</small><select value={draft.priority} onChange={e=>set('priority',e.target.value)}><option>Normal</option><option>Urgent</option><option>High</option><option>Low</option></select></span></label>
     <label className="service-control-chip control-engineer tone-slate"><span className="service-control-icon"><Icon name="user" size={18}/></span><span><small>Engineer</small><input value={draft.engineer} onChange={e=>set('engineer',e.target.value)} placeholder="Unassigned"/></span></label>
     <label className={'service-control-chip control-due '+(dueOverdue?'tone-red':'tone-slate')}><span className="service-control-icon"><Icon name="calendar" size={18}/></span><span><small>{dueOverdue?'Due Date • OVERDUE':'Due Date'}</small><input type="date" value={draft.dueDate||''} onChange={e=>set('dueDate',e.target.value)}/></span></label>
     <label className={'service-control-chip control-foc '+(draft.foc?'tone-green':'tone-slate')}><span className="service-control-icon"><Icon name="tag" size={18}/></span><span><small>FOC</small><select value={draft.foc?'Yes':'No'} onChange={e=>set('foc',e.target.value==='Yes')}><option>Yes</option><option>No</option></select></span></label>
    </div>
   </section>
   <div className="detail-tabs service-workspace-tabs">{tabs.map(t=><button type="button" key={t.key} className={tab===t.key?'active':''} onClick={()=>setTab(t.key)}><Icon name={t.icon} size={15}/><span>{t.key}</span>{t.key==='Parts Used'&&detail.parts.length>0?<b>{detail.parts.length}</b>:null}{t.key==='History'&&detail.events.length>0?<b>{detail.events.length}</b>:null}</button>)}</div>
   {tab==='Service'&&<div className="detail-panel-grid"><section className="detail-card"><div className="detail-card-head"><div><h3>Operational Details</h3><p>Keep status and responsibility current.</p></div></div><div className="form-grid four"><Field label="Reason"><select value={draft.reason} onChange={e=>set('reason',e.target.value)}><option>Repair</option><option>Calibration</option><option>Preventive Service</option><option>Installation / Commissioning</option><option>Inspection</option><option>Other</option></select></Field><Field label="Service Location"><select value={draft.serviceLocation} onChange={e=>set('serviceLocation',e.target.value)}><option>Workshop</option><option>Onsite</option><option>Other</option></select></Field><Field label="Complaint / Requirement" wide><textarea value={draft.complaint} onChange={e=>set('complaint',e.target.value)}/></Field></div></section>
    <section className="detail-card"><div className="detail-card-head"><div><h3>Inspection & Work</h3><p>Technical work remains readable and report-ready.</p></div></div><div className="detail-text-grid"><Field label="Diagnosis"><textarea value={draft.diagnosis} onChange={e=>set('diagnosis',e.target.value)} placeholder="Inspection findings / diagnosis"/></Field><Field label="Work Performed"><textarea value={draft.workPerformed} onChange={e=>set('workPerformed',e.target.value)} placeholder="Work completed during this service"/></Field><Field label="Testing / Verification"><textarea value={draft.testingVerification} onChange={e=>set('testingVerification',e.target.value)} placeholder="Testing and verification after work"/></Field><Field label="Final Result"><textarea value={draft.finalResult} onChange={e=>set('finalResult',e.target.value)} placeholder="Final service outcome"/></Field><Field label="Recommendations / Follow-up"><textarea value={draft.recommendations} onChange={e=>set('recommendations',e.target.value)} placeholder="Recommendations or next action"/></Field><Field label="Completion Date"><input type="date" value={draft.completionDate||''} onChange={e=>set('completionDate',e.target.value)}/></Field></div></section>
   </div>}
   {tab==='Received Item'&&<div className="detail-panel-grid received-grid"><section className="detail-card"><div className="detail-card-head"><div><h3>Condition When Received</h3><p>Quick evidence without turning intake into a long form.</p></div></div><div className="condition-choice">{['Good','Used','Damaged','Not Working'].map(v=><button type="button" className={draft.receivedCondition===v?'selected':''} onClick={()=>set('receivedCondition',v)} key={v}>{v}</button>)}</div><div className="detail-text-grid received-fields"><Field label="Accessories / Items Received"><textarea value={draft.receivedAccessories} onChange={e=>set('receivedAccessories',e.target.value)} placeholder="Power adapter, probe, carry case…"/></Field><Field label="Condition Remarks"><textarea value={draft.receivedRemarks} onChange={e=>set('receivedRemarks',e.target.value)} placeholder="Scratches, broken or missing items, packaging condition…"/></Field></div></section><AttachmentPanel serviceCallId={service.id} onChanged={async()=>{setDetail(await ServixApi.getServiceDetail(service.id));await onUpdated()}}/></div>}
   {tab==='Parts Used'&&<div className="detail-card"><div className="detail-card-head"><div><h3>Parts / Items Used</h3><p>Consumption history only — no warehouse stock management.</p></div><button className="secondary-button" onClick={()=>setShowPart(!showPart)}><Icon name="plus"/> Add Item</button></div>{showPart&&<div className="part-entry"><div className="form-grid four"><Field label="Part / Item" required wide><input value={part.itemName} onChange={e=>setPart({...part,itemName:e.target.value})}/></Field><Field label="Make"><input value={part.make} onChange={e=>setPart({...part,make:e.target.value})}/></Field><Field label="Model"><input value={part.model} onChange={e=>setPart({...part,model:e.target.value})}/></Field><Field label="Part Number"><input value={part.partNumber} onChange={e=>setPart({...part,partNumber:e.target.value})}/></Field><Field label="Quantity"><input type="number" min="1" value={part.quantity} onChange={e=>setPart({...part,quantity:Number(e.target.value)})}/></Field><Field label="Remarks" wide><input value={part.remarks} onChange={e=>setPart({...part,remarks:e.target.value})}/></Field></div><div className="part-entry-actions"><button className="text-button" onClick={()=>setShowPart(false)}>Cancel</button><button className="primary-button" disabled={busy} onClick={addPart}>Add to Service</button></div></div>}<div className="parts-detail-list">{detail.parts.map(p=><div className="part-detail-row" key={p.id}><span className="part-qty">{p.quantity}</span><span><strong>{p.itemName}</strong><small>{[p.make,p.model,p.partNumber].filter(Boolean).join(' • ')||'No reference details'}</small></span><span><small>{p.usedAt}</small><strong>{p.remarks||'—'}</strong></span></div>)}{!detail.parts.length&&<EmptyState title="No parts recorded" detail="Add only items actually used during this service."/>}</div></div>}
   {tab==='Notes'&&<div className="notes-workspace"><section className="detail-card note-card"><div className="detail-card-head"><div><h3>Add Service Note</h3><p>Record an engineer update, customer discussion or next action. Notes are appended and never replace earlier entries.</p></div></div><div className="note-format-toolbar">{[{label:'Heading',prefix:'# '},{label:'Bullet list',prefix:'- '},{label:'Numbered list',prefix:'1. '}].map(f=><button type="button" className="small-button" key={f.label} onClick={()=>setNote(n=>n+(n&&!n.endsWith('\n')?'\n':'')+f.prefix)}>{f.label}</button>)}</div><textarea aria-label="New service note" value={note} onChange={e=>setNote(e.target.value)} placeholder="Type your service update… Use headings or lists to keep it easy to read."/>{note.trim()&&<div className="note-preview"><small>Preview</small><NoteContent text={note}/></div>}<button className="primary-button" disabled={busy||!note.trim()} onClick={addNote}>Save Note</button></section><section className="detail-card"><div className="detail-card-head"><h3>Saved Notes</h3><span className="soft-chip">{detail.events.filter(e=>e.eventType==='Note').length} notes</span></div>{detail.events.filter(e=>e.eventType==='Note').map(e=><article className="saved-note" key={e.id}><header><strong>{e.actor}</strong><small>{e.createdAt}</small></header><NoteContent text={e.note}/></article>)}{!detail.events.some(e=>e.eventType==='Note')&&<EmptyState title="No service notes yet" detail="Saved notes appear here and in the full activity history."/>}</section></div>}
   {tab==='History'&&<div className="history-workspace"><section className="detail-card history-card"><div className="detail-card-head"><div><h3>Complete Activity</h3><p>Newest activity first. Print or export this Service ID audit trail when required.</p></div><div className="history-actions"><span className="soft-chip">{detail.events.length} events</span><button type="button" className="small-button history-action-button" onClick={()=>{const rows=detail.events.map(ev=>({dateTime:ev.createdAt,user:ev.actor,action:ev.eventType,serviceId:detail.serviceId,details:historyEventDetails(ev),context:detail.client+' • '+detail.equipment,status:draft.status}));printHistoryDocument('Service History',detail.serviceId+' • '+detail.client,rows,['Equipment: '+detail.equipment+(detail.serialNumber?' • S/N '+detail.serialNumber:''),'Current Status: '+draft.status])}}><Icon name="print" size={14}/> Print</button><button type="button" className="small-button history-action-button" onClick={()=>{const rows=detail.events.map(ev=>({dateTime:ev.createdAt,user:ev.actor,action:ev.eventType,serviceId:detail.serviceId,details:historyEventDetails(ev),context:detail.client+' • '+detail.equipment,status:draft.status}));historyRowsToCsv(detail.serviceId+'-history',rows)}}><Icon name="export" size={14}/> CSV</button></div></div><div className="timeline">{detail.events.map(ev=><div className="timeline-row" key={ev.id}><i/><div><div><strong>{ev.eventType}</strong><small>{ev.createdAt}</small></div><p>{historyEventDetails(ev)}</p><span>{ev.actor}</span></div></div>)}</div></section></div>}
  </>}
 </Modal>;
}

function ServiceCallsView({data,onRefresh}:{data:DashboardData,onRefresh:()=>void}){
 const [search,setSearch]=React.useState(''); const [status,setStatus]=React.useState('All'); const [reason,setReason]=React.useState('All'); const [coverage,setCoverage]=React.useState('All'); const [showNew,setShowNew]=React.useState(false); const [selectedService,setSelectedService]=React.useState(null as ServiceCall|null); const [selected,setSelected]=React.useState([] as number[]);
 const rows=data.services.filter(x=>(status==='All'||x.status===status)&&(reason==='All'||x.reason===reason)&&(coverage==='All'||x.coverage===coverage)&&(`${x.serviceId} ${x.client} ${x.equipment} ${x.reason} ${x.engineer} ${x.serialNumber||''}`.toLowerCase().includes(search.toLowerCase())));
 const allVisibleSelected=rows.length>0&&rows.every(r=>selected.includes(r.id));
 const toggleAll=()=>setSelected(allVisibleSelected?selected.filter(id=>!rows.some(r=>r.id===id)):Array.from(new Set([...selected,...rows.map(r=>r.id)])));
 const toggleOne=(id:number)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 return <div className="module-content"><PageHeader title="Service Calls" subtitle="Create, track and close service requests while retaining the full history" actions={<button className="primary-button" onClick={()=>setShowNew(true)}><Icon name="plus"/> New Service Call</button>}/>
  <Toolbar><SearchBox value={search} onChange={setSearch} placeholder="Search Service ID, client, equipment, serial, reason..."/><select className="filter-select" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Open</option><option>In Progress</option><option>Pending</option><option>Closed</option></select><select className="filter-select" value={reason} onChange={e=>setReason(e.target.value)}><option>All</option><option>Repair</option><option>Calibration</option><option>Preventive Service</option><option>Installation / Commissioning</option><option>Inspection</option><option>Other</option></select><select className="filter-select" value={coverage} onChange={e=>setCoverage(e.target.value)}><option>All</option><option>Warranty</option><option>AMC</option><option>Out of Coverage</option></select><button className="text-button" onClick={()=>{setSearch('');setStatus('All');setReason('All');setCoverage('All')}}>Clear All</button><button className="secondary-button"><Icon name="export"/> Export</button></Toolbar>
  <div className="results-summary"><span><strong>{rows.length}</strong> matching service calls {selected.length>0&&<>• <strong>{selected.length}</strong> selected</>}</span><span>Open a Service ID to work on the complete record.</span></div>
  <section className="table-card"><div className="data-table service-table"><div className="tr th"><span><input type="checkbox" checked={allVisibleSelected} onChange={toggleAll}/></span><span>Service ID</span><span>Opened</span><span>Client</span><span>Equipment</span><span>Reason</span><span>Engineer</span><span>Status</span><span>Coverage</span><span>Payment</span></div>{rows.map(x=><div className="tr service-record-row" key={x.id} role="button" tabIndex={0} onClick={()=>setSelectedService(x)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelectedService(x)}}}><span className="service-select-cell" onClick={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggleOne(x.id)} aria-label={'Select '+x.serviceId}/></span><span className="service-primary-cell"><span className="service-id-anchor"><Icon name="service" size={15}/><span><strong>{x.serviceId}</strong><small>Open workspace</small></span></span></span><span>{x.openedDate}</span><span><strong>{x.client}</strong></span><span><strong>{x.equipment}</strong><small>{x.make} {x.model} {x.serialNumber&&`• ${x.serialNumber}`}</small></span><span>{x.reason}</span><span>{x.engineer||'—'}</span><span><StatusBadge value={x.status}/></span><span>{x.coverage}{x.foc&&<small> • FOC</small>}</span><span className="service-payment-cell"><StatusBadge value={x.paymentStatus}/><Icon name="chevron" size={15}/></span></div>)}</div>{!rows.length&&<EmptyState title="No matching service calls" detail="Adjust the filters or create a new service call."/>}</section>
  {showNew&&<ServiceCallForm onClose={()=>setShowNew(false)} onCreated={onRefresh}/>} {selectedService&&<ServiceDetailModal service={selectedService} onClose={()=>setSelectedService(null)} onUpdated={onRefresh}/>}</div>;
}
