const initialServiceDraft={openedDate:new Date().toISOString().slice(0,10),client:'',contact:'',mobile:'',email:'',equipment:'',make:'',model:'',serialNumber:'',reason:'Repair',complaint:'',priority:'Normal',engineer:'',serviceLocation:'Workshop',dueDate:'',status:'Open',coverage:'Out of Coverage',foc:false,quoteStatus:'No Quote',paymentStatus:'Pending'};
function ServiceCallForm({onClose,onCreated}:{onClose:()=>void,onCreated:()=>void}){
 const [draft,setDraft]=React.useState({...initialServiceDraft}); const [busy,setBusy]=React.useState(false); const [error,setError]=React.useState('');
 const set=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 const save=async()=>{if(!draft.client||!draft.equipment||!draft.reason||!draft.complaint){setError('Client, equipment, reason and complaint are required.');return;} setBusy(true);setError('');try{await ServixApi.createServiceCall(draft);onCreated();onClose()}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 return <Modal title="New Service Call" subtitle="Fast intake with secondary details revealed only when needed" onClose={onClose} wide footer={<><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy} onClick={save}>{busy?'Saving...':'Save Service Call'}</button></>}>
  {error&&<div className="form-error">{error}</div>}
  <div className="form-section"><div className="section-number">1</div><div className="form-section-body"><div className="section-title"><h3>Client & Equipment</h3><p>Select existing records or enter the service intake information.</p></div><div className="form-grid four"><Field label="Client Name" required wide><input value={draft.client} onChange={e=>set('client',e.target.value)} placeholder="Search or type client"/></Field><Field label="Contact Person"><input value={draft.contact} onChange={e=>set('contact',e.target.value)}/></Field><Field label="Mobile"><input value={draft.mobile} onChange={e=>set('mobile',e.target.value)}/></Field><Field label="Email"><input value={draft.email} onChange={e=>set('email',e.target.value)} type="email"/></Field><Field label="Equipment" required wide><input value={draft.equipment} onChange={e=>set('equipment',e.target.value)} placeholder="e.g. Audiometer"/></Field><Field label="Make"><input value={draft.make} onChange={e=>set('make',e.target.value)}/></Field><Field label="Model"><input value={draft.model} onChange={e=>set('model',e.target.value)}/></Field><Field label="Serial Number"><input value={draft.serialNumber} onChange={e=>set('serialNumber',e.target.value)}/></Field></div></div></div>
  <div className="form-section"><div className="section-number">2</div><div className="form-section-body"><div className="section-title"><h3>Service Details</h3><p>Only the operational information needed to start the call.</p></div><div className="form-grid four"><Field label="Opened Date" required><input type="date" value={draft.openedDate} onChange={e=>set('openedDate',e.target.value)}/></Field><Field label="Reason" required><select value={draft.reason} onChange={e=>set('reason',e.target.value)}><option>Repair</option><option>Calibration</option><option>Preventive Service</option><option>Installation / Commissioning</option><option>Inspection</option><option>Other</option></select></Field><Field label="Priority"><select value={draft.priority} onChange={e=>set('priority',e.target.value)}><option>Normal</option><option>Urgent</option><option>High</option><option>Low</option></select></Field><Field label="Status"><select value={draft.status} onChange={e=>set('status',e.target.value)}><option>Open</option><option>In Progress</option><option>Pending</option><option>Closed</option></select></Field><Field label="Complaint / Requirement" required wide><textarea value={draft.complaint} onChange={e=>set('complaint',e.target.value)} placeholder="Describe the issue reported by the client"/></Field><Field label="Assigned Engineer"><input value={draft.engineer} onChange={e=>set('engineer',e.target.value)} placeholder="Select engineer"/></Field><Field label="Service Location"><select value={draft.serviceLocation} onChange={e=>set('serviceLocation',e.target.value)}><option>Workshop</option><option>Onsite</option><option>Other</option></select></Field><Field label="Due Date"><input type="date" value={draft.dueDate} onChange={e=>set('dueDate',e.target.value)}/></Field></div></div></div>
  <div className="form-section"><div className="section-number">3</div><div className="form-section-body"><div className="section-title"><h3>Coverage / Commercial</h3><p>Compact controls keep the form simple.</p></div><div className="choice-group"><div><span className="choice-label">Coverage</span>{['Warranty','AMC','Out of Coverage'].map(v=><button className={draft.coverage===v?'selected':''} onClick={()=>set('coverage',v)} key={v}>{v}</button>)}</div><div><span className="choice-label">FOC</span>{[true,false].map(v=><button className={draft.foc===v?'selected':''} onClick={()=>set('foc',v)} key={String(v)}>{v?'Yes':'No'}</button>)}</div><div><span className="choice-label">Quote</span>{['Quote Sent','No Quote','Phone Discussed'].map(v=><button className={draft.quoteStatus===v?'selected':''} onClick={()=>set('quoteStatus',v)} key={v}>{v}</button>)}</div><div><span className="choice-label">Payment</span>{['Pending','Paid'].map(v=><button className={draft.paymentStatus===v?'selected':''} onClick={()=>set('paymentStatus',v)} key={v}>{v}</button>)}</div></div></div></div>
 </Modal>;
}
function ServiceCallsView({data,onRefresh}:{data:DashboardData,onRefresh:()=>void}){
 const [search,setSearch]=React.useState(''); const [status,setStatus]=React.useState('All'); const [showNew,setShowNew]=React.useState(false);
 const rows=data.services.filter(x=>(status==='All'||x.status===status)&&(`${x.serviceId} ${x.client} ${x.equipment} ${x.reason} ${x.engineer}`.toLowerCase().includes(search.toLowerCase())));
 return <div className="module-content"><PageHeader title="Service Calls" subtitle="Create, track and close service requests while retaining the full history" actions={<button className="primary-button" onClick={()=>setShowNew(true)}><Icon name="plus"/> New Service Call</button>}/>
  <Toolbar><SearchBox value={search} onChange={setSearch} placeholder="Search Service ID, client, equipment, reason..."/><select className="filter-select" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Open</option><option>In Progress</option><option>Pending</option><option>Closed</option></select><select className="filter-select"><option>All Reasons</option><option>Repair</option><option>Calibration</option><option>Preventive Service</option></select><select className="filter-select"><option>All Coverage</option><option>Warranty</option><option>AMC</option><option>Out of Coverage</option></select><button className="secondary-button"><Icon name="export"/> Export</button></Toolbar>
  <div className="results-summary"><span><strong>{rows.length}</strong> matching service calls</span><span>Filters are combinable and exports respect the filtered set.</span></div>
  <section className="table-card"><div className="data-table service-table"><div className="tr th"><span><input type="checkbox"/></span><span>Service ID</span><span>Opened</span><span>Client</span><span>Equipment</span><span>Reason</span><span>Engineer</span><span>Status</span><span>Coverage</span><span>Payment</span></div>{rows.map(x=><div className="tr" key={x.id}><span><input type="checkbox"/></span><span><strong className="linkish">{x.serviceId}</strong></span><span>{x.openedDate}</span><span><strong>{x.client}</strong></span><span><strong>{x.equipment}</strong><small>{x.make} {x.model} {x.serialNumber&&`• ${x.serialNumber}`}</small></span><span>{x.reason}</span><span>{x.engineer||'—'}</span><span><StatusBadge value={x.status}/></span><span>{x.coverage}{x.foc&&<small> • FOC</small>}</span><span><StatusBadge value={x.paymentStatus}/></span></div>)}</div>{!rows.length&&<EmptyState title="No matching service calls" detail="Adjust the filters or create a new service call."/>}</section>
  {showNew&&<ServiceCallForm onClose={()=>setShowNew(false)} onCreated={onRefresh}/>}</div>;
}
