function SettingsView({data,onRefresh}:{data:DashboardData,onRefresh:()=>void}){
 const sync=data.sync;
 const [showUser,setShowUser]=React.useState(false);
 const [draft,setDraft]=React.useState({displayName:'',username:'',password:'',role:'Office User'});
 const [error,setError]=React.useState(''); const [busy,setBusy]=React.useState(false);
 const saveUser=async()=>{setError('');if(!draft.displayName||!draft.username||!draft.password){setError('Display name, username and password are required.');return}setBusy(true);try{await ServixApi.createUser(draft);await onRefresh();setShowUser(false);setDraft({displayName:'',username:'',password:'',role:'Office User'})}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 return <div className="module-content"><PageHeader title="Users & Settings" subtitle="Administrator-only configuration and reference data"/><div className="settings-grid">
  <section className="card"><h3>Service ID Series</h3><p>Configurable prefix, digit width and next number. The production sequence will be confirmed before deployment.</p><div className="inline-fields"><Field label="Prefix"><input value="SRV-" readOnly/></Field><Field label="Next Number"><input value="10001" readOnly/></Field><Field label="Digits"><input value="5" readOnly/></Field></div></section>
  <section className="card"><h3>Google Form Intake</h3><p>Field mapping will allow the Google Form to change without breaking SERVIX.</p><div className="setting-status"><span>Integration status</span><StatusBadge value={sync.configured?'Configured':'Not configured'}/></div><div className="setting-status"><span>Last successful sync</span><strong>{sync.lastSuccessfulSync||'—'}</strong></div><button className="secondary-button">Configure Mapping</button></section>
  <section className="card users-card"><div className="card-head"><div><h3>Users & Roles</h3><p>Simple user creation with the premium NEO-style approach.</p></div><button className="secondary-button" onClick={()=>setShowUser(true)}><Icon name="plus"/> Add User</button></div><div className="compact-list user-list">{data.users.map(u=><div className="user-row" key={u.id}><span className="avatar">{u.displayName.slice(0,1).toUpperCase()}</span><span><strong>{u.displayName}</strong><small>{u.username}</small></span><StatusBadge value={u.role}/><small>{u.active?'Active':'Inactive'}</small></div>)}</div></section>
  <section className="card"><h3>Backup & Data</h3><p>Backups are separate from exports and include the database plus linked attachments.</p><button className="secondary-button">Open Data Management</button></section>
 </div>
 {showUser&&<Modal title="Add User" subtitle="Keep user creation simple and role-based" onClose={()=>setShowUser(false)} footer={<><button className="secondary-button" onClick={()=>setShowUser(false)}>Cancel</button><button className="primary-button" disabled={busy} onClick={saveUser}>{busy?'Saving...':'Create User'}</button></>}><div className="form-grid"><Field label="Display Name" required><input value={draft.displayName} onChange={e=>setDraft({...draft,displayName:e.target.value})}/></Field><Field label="Username" required><input value={draft.username} onChange={e=>setDraft({...draft,username:e.target.value})}/></Field><Field label="Password" required><input type="password" value={draft.password} onChange={e=>setDraft({...draft,password:e.target.value})}/></Field><Field label="Role"><select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option>Office User</option><option>Administrator</option><option>Read Only</option></select></Field></div>{error&&<div className="form-error">{error}</div>}</Modal>}
 </div>;
}
