function SettingsView({data,onRefresh}:{data:DashboardData,onRefresh:()=>void}){
 const sync=data.sync;
 const [showUser,setShowUser]=React.useState(false); const [showAbout,setShowAbout]=React.useState(false); const [showGoogle,setShowGoogle]=React.useState(false);
 const [draft,setDraft]=React.useState({displayName:'',username:'',password:'',role:'Office User'});
 const [google,setGoogle]=React.useState(null as GoogleSyncConfig|null);
 const [googleDraft,setGoogleDraft]=React.useState(null as GoogleSyncConfigDraft|null);
 const [error,setError]=React.useState(''); const [busy,setBusy]=React.useState(false); const [syncMessage,setSyncMessage]=React.useState('');
 const saveUser=async()=>{setError('');if(!draft.displayName||!draft.username||!draft.password){setError('Display name, username and password are required.');return}setBusy(true);try{await ServixApi.createUser(draft);await onRefresh();setShowUser(false);setDraft({displayName:'',username:'',password:'',role:'Office User'})}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 const openGoogle=async()=>{setBusy(true);setError('');setSyncMessage('');try{const cfg=await ServixApi.getGoogleSyncConfig();setGoogle(cfg);setGoogleDraft({...cfg,serviceAccountJson:'',clearCredentials:false});setShowGoogle(true)}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 const setG=(k:keyof GoogleSyncConfigDraft,v:any)=>setGoogleDraft(d=>d?({...d,[k]:v}):d);
 const saveGoogle=async()=>{if(!googleDraft)return;setBusy(true);setError('');try{const cfg=await ServixApi.saveGoogleSyncConfig(googleDraft);setGoogle(cfg);setGoogleDraft({...cfg,serviceAccountJson:'',clearCredentials:false});await onRefresh();setSyncMessage(cfg.serviceAccountConfigured?'Google intake configuration saved.':'Source mapping saved. Add service-account JSON to enable live sync.')}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 const testGoogle=async()=>{if(!googleDraft)return;setBusy(true);setError('');setSyncMessage('');try{const cfg=await ServixApi.saveGoogleSyncConfig(googleDraft);setGoogle(cfg);setGoogleDraft({...cfg,serviceAccountJson:'',clearCredentials:false});if(!cfg.serviceAccountConfigured)throw new Error('Add the service-account JSON before testing live sync.');const s=await ServixApi.syncGoogleForm();setSyncMessage(s.message);await onRefresh()}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};
 return <div className="module-content"><PageHeader title="Users & Settings" subtitle="Administrator-only configuration and reference data"/><div className="settings-grid"><DisplayPreferences/>
  <SequenceSettings/>
  <section className="card google-setting-card"><div className="card-head"><div><h3>Google Form Intake</h3><p>Read-only Google Sheet sync into the Incoming Requests review queue.</p></div><StatusBadge value={sync.configured?'Configured':'Not configured'}/></div><div className="setting-status"><span>Last successful sync</span><strong>{sync.lastSuccessfulSync||'—'}</strong></div><div className="setting-status"><span>New requests waiting</span><strong>{sync.newCount}</strong></div><button className="secondary-button" disabled={busy} onClick={openGoogle}><Icon name="settings" size={14}/> Configure Google Intake</button></section>
  <section className="card users-card"><div className="card-head"><div><h3>Users & Roles</h3><p>Simple user creation with the premium NEO-style approach.</p></div><button className="secondary-button" onClick={()=>setShowUser(true)}><Icon name="plus"/> Add User</button></div><div className="compact-list user-list">{data.users.map(u=><div className="user-row" key={u.id}><span className="avatar">{u.displayName.slice(0,1).toUpperCase()}</span><span><strong>{u.displayName}</strong><small>{u.username}</small></span><StatusBadge value={u.role}/><small>{u.active?'Active':'Inactive'}</small></div>)}</div></section>
  <section className="card"><h3>Backup & Data</h3><p>Backups are separate from exports and include the database plus linked attachments.</p><button className="secondary-button">Open Data Management</button></section>
  <section className="card"><h3>About SERVIX</h3><p>Application information is kept here so it is available when required without occupying the everyday workspace.</p><div className="setting-status"><span>Publisher</span><strong>Yogesh Gaurav</strong></div><div className="setting-status"><span>Application</span><strong>SERVIX</strong></div><button className="secondary-button" onClick={()=>setShowAbout(true)}>Application Information</button></section>
 </div>
 {showGoogle&&googleDraft&&<Modal title="Google Form Intake" subtitle="Read-only Sheet connection • credentials remain only in this local SERVIX database" onClose={()=>!busy&&setShowGoogle(false)} wide className="google-config-modal" footer={<><button className="secondary-button" disabled={busy} onClick={()=>setShowGoogle(false)}>Close</button><button className="secondary-button" disabled={busy} onClick={testGoogle}><Icon name="refresh" size={14}/> Save & Sync Test</button><button className="primary-button" disabled={busy} onClick={saveGoogle}>{busy?'Saving...':'Save Configuration'}</button></>}>
   <div className="google-config-layout">
    <section className="detail-card"><div className="detail-card-head"><div><h3>Google Sheet Source</h3><p>SERVIX only reads the Form Responses sheet. It never writes back to Google.</p></div>{google?.serviceAccountConfigured?<span className="soft-chip">Credential saved locally</span>:<span className="soft-chip">Credential required</span>}</div>
     <div className="form-grid two google-source-grid"><Field label="Spreadsheet ID" required wide><input value={googleDraft.sheetId} onChange={e=>setG('sheetId',e.target.value)}/></Field><Field label="Sheet Tab" required><input value={googleDraft.sheetName} onChange={e=>setG('sheetName',e.target.value)}/></Field><Field label="Service Account"><input value={google?.serviceAccountEmail||'Not configured'} readOnly/></Field></div>
     <Field label={google?.serviceAccountConfigured?'Replace Service-Account JSON (leave blank to keep current)':'Service-Account JSON'}><textarea className="credential-box" value={googleDraft.serviceAccountJson} onChange={e=>setG('serviceAccountJson',e.target.value)} placeholder='Paste the read-only Google service-account JSON here. Share the Sheet with its client_email as Viewer.'/></Field>
     {google?.serviceAccountConfigured&&<label className="google-clear-credential"><input type="checkbox" checked={googleDraft.clearCredentials} onChange={e=>setG('clearCredentials',e.target.checked)}/><span>Remove the currently stored Google credential</span></label>}
     <div className="google-security-note"><Icon name="shield" size={17}/><div><strong>Local credential only</strong><p>The credential is stored in this SERVIX installation's local SQLite settings. It is not committed to GitHub and is not packaged inside the installer.</p></div></div>
    </section>
    <section className="detail-card"><div className="detail-card-head"><div><h3>Field Mapping</h3><p>Map SERVIX fields to the exact header names in row 1. Other columns remain preserved in the immutable original snapshot.</p></div></div>
     <div className="form-grid two">
      <Field label="Timestamp" required><input value={googleDraft.timestampHeader} onChange={e=>setG('timestampHeader',e.target.value)}/></Field>
      <Field label="Client / Organisation" required><input value={googleDraft.clientHeader} onChange={e=>setG('clientHeader',e.target.value)}/></Field>
      <Field label="Contact Person"><input value={googleDraft.contactHeader} onChange={e=>setG('contactHeader',e.target.value)}/></Field>
      <Field label="Mobile" required><input value={googleDraft.mobileHeader} onChange={e=>setG('mobileHeader',e.target.value)}/></Field>
      <Field label="Email" required><input value={googleDraft.emailHeader} onChange={e=>setG('emailHeader',e.target.value)}/></Field>
      <Field label="Equipment" required><input value={googleDraft.equipmentHeader} onChange={e=>setG('equipmentHeader',e.target.value)}/></Field>
      <Field label="Make"><input value={googleDraft.makeHeader} onChange={e=>setG('makeHeader',e.target.value)}/></Field>
      <Field label="Model"><input value={googleDraft.modelHeader} onChange={e=>setG('modelHeader',e.target.value)}/></Field>
      <Field label="Serial Number" required><input value={googleDraft.serialHeader} onChange={e=>setG('serialHeader',e.target.value)}/></Field>
      <Field label="Reason for Sending"><input value={googleDraft.reasonHeader} onChange={e=>setG('reasonHeader',e.target.value)}/></Field>
      <Field label="Complaint / Requirement" required wide><input value={googleDraft.complaintHeader} onChange={e=>setG('complaintHeader',e.target.value)}/></Field>
     </div>
     <div className="google-map-note"><strong>Current HAC form:</strong><span>Accessories Sent, Courier / AWB Number and Confirmation are also retained automatically in the original submission snapshot.</span></div>
    </section>
   </div>
   {syncMessage&&<div className="sync-success">{syncMessage}</div>}{error&&<div className="form-error">{error}</div>}
  </Modal>}
 {showUser&&<Modal title="Add User" subtitle="Keep user creation simple and role-based" onClose={()=>setShowUser(false)} footer={<><button className="secondary-button" onClick={()=>setShowUser(false)}>Cancel</button><button className="primary-button" disabled={busy} onClick={saveUser}>{busy?'Saving...':'Create User'}</button></>}><div className="form-grid"><Field label="Display Name" required><input value={draft.displayName} onChange={e=>setDraft({...draft,displayName:e.target.value})}/></Field><Field label="Username" required><input value={draft.username} onChange={e=>setDraft({...draft,username:e.target.value})}/></Field><Field label="Password" required><input type="password" value={draft.password} onChange={e=>setDraft({...draft,password:e.target.value})}/></Field><Field label="Role"><select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option>Office User</option><option>Administrator</option><option>Read Only</option></select></Field></div>{error&&<div className="form-error">{error}</div>}</Modal>}
 {showAbout&&<Modal title="About SERVIX" subtitle="Application and publisher information" onClose={()=>setShowAbout(false)} footer={<button className="primary-button" onClick={()=>setShowAbout(false)}>Close</button>}><div className="about-app"><div className="about-brand"><img src="assets/servix-logo.png" alt="SERVIX"/><div><h3>SERVIX</h3><p>Service Management</p></div></div><div className="setting-status"><span>Version</span><strong>0.1.0 Rebuild</strong></div><div className="setting-status"><span>Publisher / Developer</span><strong>Yogesh Gaurav</strong></div><div className="setting-status"><span>Platform</span><strong>Windows Desktop</strong></div><div className="setting-status"><span>Technology</span><strong>Tauri • Rust • React • TypeScript • SQLite</strong></div><div className="setting-status"><span>Data Mode</span><strong>Offline-first • Local database</strong></div><p className="about-note">SERVIX is a standalone service-management application for service calls, client and equipment history, received-item evidence, parts usage, reports and operational data management.</p></div></Modal>}
 </div>;
}