use crate::{state::AppState,models::SessionUser};
use rusqlite::{params,Connection,OptionalExtension};
use serde::{Deserialize,Serialize};
use serde_json::{Value,json};
use sha2::{Digest,Sha256};
use std::{collections::{BTreeMap,HashSet},fs,path::PathBuf};
use tauri::State;
type Row=BTreeMap<String,String>;
fn err(e:impl std::fmt::Display)->String{format!("Data operation failed: {e}")}
fn actor(state:&AppState,admin:bool)->Result<SessionUser,String>{let u=state.session.lock().map_err(err)?.clone().ok_or("Please sign in again.")?;if admin&&u.role!="Administrator"{return Err("Administrator permission is required.".into())}Ok(u)}
fn v<'a>(r:&'a Row,k:&str)->&'a str{r.get(k).map(|s|s.trim()).unwrap_or("")}
fn date(s:&str)->bool{s.len()==10&&chrono::NaiveDate::parse_from_str(s,"%Y-%m-%d").is_ok()}
fn hash(s:&str)->String{hex::encode(Sha256::digest(s.as_bytes()))}
#[derive(Deserialize)] pub struct ImportDraft{pub kind:String,pub rows:Vec<Row>}
#[derive(Serialize)] #[serde(rename_all="camelCase")] pub struct Review{pub token:String,pub ready:usize,pub skipped:usize,pub errors:usize,pub rows:Vec<Value>}
fn review(db:&Connection,d:&ImportDraft)->Result<Review,String>{
 if !["clients","equipment","service_calls","notes"].contains(&d.kind.as_str())||d.rows.is_empty()||d.rows.len()>10000{return Err("Select a supported CSV with 1–10,000 rows.".into())}
 let mut rows=Vec::new();let mut seen=HashSet::new();let mut mobiles=HashSet::new();let mut emails=HashSet::new();let mut serials=HashSet::new();let(mut ready,mut skipped,mut errors)=(0,0,0);
 for (i,r) in d.rows.iter().enumerate(){let mut problems=Vec::new();let key=match d.kind.as_str(){"clients"=>v(r,"code"),"equipment"=>v(r,"servix_equipment_id"),"service_calls"=>v(r,"service_id"),_=>v(r,"import_key")};
 if key.is_empty(){problems.push("Unique ID is required".to_string())}else if key.len()>64||!key.bytes().all(|b|b.is_ascii_alphanumeric()||b'-'==b||b'_'==b||b'.'==b){problems.push("IDs must use 1–64 letters, digits, hyphens, underscores or dots".into())}if !seen.insert(key.to_lowercase()){problems.push("Repeated ID within this file".into())}
 if r.values().any(|s|s.len()>20000){problems.push("A cell exceeds 20,000 characters".into())}
 let exists=match d.kind.as_str(){"clients"=>db.query_row("SELECT EXISTS(SELECT 1 FROM clients WHERE lower(code)=lower(?1))",[key],|r|r.get::<_,bool>(0)),"equipment"=>db.query_row("SELECT EXISTS(SELECT 1 FROM equipment WHERE lower(servix_equipment_id)=lower(?1))",[key],|r|r.get(0)),"service_calls"=>db.query_row("SELECT EXISTS(SELECT 1 FROM service_calls WHERE lower(service_id)=lower(?1))",[key],|r|r.get(0)),_=>db.query_row("SELECT EXISTS(SELECT 1 FROM audit_log WHERE entity='CSV Note' AND record_id=?1)",[key],|r|r.get(0))}.map_err(err)?;
 if !exists{match d.kind.as_str(){
 "clients"=>{if v(r,"name").is_empty(){problems.push("Client name is required".into())}let mobile=v(r,"mobile");let email=v(r,"email");let digits:String=mobile.chars().filter(|c|c.is_ascii_digit()).collect();if !digits.is_empty()&&!mobiles.insert(digits.clone()){problems.push("Repeated mobile within this file".into())}if !email.is_empty()&&!emails.insert(email.to_lowercase()){problems.push("Repeated email within this file".into())}if !digits.is_empty()||!email.is_empty(){let mut q=db.prepare("SELECT mobile,email FROM clients").map_err(err)?;let matches=q.query_map([],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?))).map_err(err)?;for m in matches{let(m,e)=m.map_err(err)?;let md:String=m.chars().filter(|c|c.is_ascii_digit()).collect();if !digits.is_empty()&&digits==md||!email.is_empty()&&email.eq_ignore_ascii_case(e.trim()){problems.push("Mobile or email already belongs to a client; review manually".into());break}}}},
 "equipment"=>{let client=lookup(db,"clients","code",v(r,"client_code"))?;if client.is_none(){problems.push("Client code was not found; import clients first".into())}if v(r,"make").is_empty()||v(r,"model").is_empty()||v(r,"serial_number").is_empty(){problems.push("Make, model and serial number are required".into())}if !serials.insert(format!("{}:{}",v(r,"client_code").to_lowercase(),v(r,"serial_number").to_lowercase())){problems.push("Repeated client and serial within this file".into())}if let Some(id)=client{let duplicate:bool=db.query_row("SELECT EXISTS(SELECT 1 FROM equipment WHERE client_id=?1 AND lower(trim(serial_number))=lower(?2))",params![id,v(r,"serial_number")],|r|r.get(0)).map_err(err)?;if duplicate{problems.push("Serial number already exists for this client".into())}}for k in ["warranty_until","amc_until"]{if !v(r,k).is_empty()&&!date(v(r,k)){problems.push(format!("{k} must be YYYY-MM-DD"))}}if !v(r,"coverage").is_empty()&&!["Warranty","AMC","Out of Coverage"].contains(&v(r,"coverage")){problems.push("Invalid coverage".into())}},
 "service_calls"=>{let cid=lookup(db,"clients","code",v(r,"client_code"))?;let eid=lookup(db,"equipment","servix_equipment_id",v(r,"equipment_id"))?;if cid.is_none()||eid.is_none(){problems.push("Existing client code and equipment ID are required".into())}if let(Some(c),Some(e))=(cid,eid){let owner:Option<i64>=db.query_row("SELECT client_id FROM equipment WHERE id=?1",[e],|r|r.get(0)).map_err(err)?;if owner!=Some(c){problems.push("Equipment does not belong to this client".into())}}
 if !date(v(r,"opened_date")){problems.push("Opened date must be YYYY-MM-DD".into())}if v(r,"complaint").is_empty()||v(r,"reason").is_empty(){problems.push("Reason and complaint are required".into())}let status=if v(r,"status").is_empty(){"Open"}else{v(r,"status")};if !["Open","In Progress","Pending","Closed"].contains(&status){problems.push("Invalid status".into())}if status=="Pending"&&v(r,"status_reason").is_empty(){problems.push("Pending status requires a reason".into())}if status=="Closed"&&(v(r,"final_result").is_empty()||!date(v(r,"completion_date"))||v(r,"completion_date")<v(r,"opened_date")){problems.push("Closed calls require result and completion date on/after opened date".into())}for(k,allowed)in [("coverage",vec!["Warranty","AMC","Out of Coverage"]),("priority",vec!["Normal","High","Urgent","Low"]),("quote_status",vec!["No Quote","Quote Sent"]),("payment_status",vec!["Pending","Paid"])]{if !v(r,k).is_empty()&&!allowed.contains(&v(r,k)){problems.push(format!("Invalid {k}"))}}if !v(r,"foc").is_empty()&&!["0","1","true","false","Yes","No"].contains(&v(r,"foc")){problems.push("FOC must be Yes/No or 1/0".into())}for k in ["due_date","follow_up_date"]{if !v(r,k).is_empty()&&!date(v(r,k)){problems.push(format!("{k} must be YYYY-MM-DD"))}}},
 _=>{if lookup(db,"service_calls","service_id",v(r,"service_id"))?.is_none(){problems.push("Service ID was not found".into())}if v(r,"note").is_empty(){problems.push("Note is required".into())}if !date(v(r,"date")){problems.push("Note date must be YYYY-MM-DD".into())}}
 }}
 let disposition=if !problems.is_empty(){errors+=1;"Error"}else if exists{skipped+=1;"Existing — skipped"}else{ready+=1;"Ready"};rows.push(json!({"row":i+2,"id":key,"status":disposition,"message":problems.join("; ")}));
 }
 let fingerprint:String=db.query_row("SELECT (SELECT COUNT(*) FROM audit_log)||':'||(SELECT coalesce(MAX(id),0) FROM audit_log)||':'||(SELECT COUNT(*) FROM clients)||':'||(SELECT COUNT(*) FROM equipment)||':'||(SELECT COUNT(*) FROM service_calls)",[],|r|r.get(0)).map_err(err)?;
 let token=hash(&format!("{}{}{}",serde_json::to_string(&d.rows).map_err(err)?,d.kind,fingerprint));Ok(Review{token,ready,skipped,errors,rows})
}
fn lookup(db:&Connection,table:&str,column:&str,value:&str)->Result<Option<i64>,String>{db.query_row(&format!("SELECT id FROM {table} WHERE {column}=?1 COLLATE NOCASE"),[value],|r|r.get(0)).optional().map_err(err)}
#[tauri::command] pub fn preview_csv(state:State<'_,AppState>,draft:ImportDraft)->Result<Review,String>{actor(&state,true)?;let db=state.db.lock().map_err(err)?;review(&db,&draft)}
fn commit(db:&mut Connection,u:&SessionUser,d:&ImportDraft,token:&str)->Result<usize,String>{let r=review(db,d)?;if r.token!=token{return Err("Data changed after preview. Validate this import again.".into())}if r.errors>0||r.ready==0{return Err("Resolve all errors and provide at least one new row.".into())}let tx=db.transaction().map_err(err)?;let now=chrono::Local::now().format("%Y-%m-%d %H:%M:%S").to_string();
 for(i,row)in d.rows.iter().enumerate(){if r.rows[i]["status"]!="Ready"{continue}match d.kind.as_str(){
 "clients"=>{tx.execute("INSERT INTO clients(code,name,contact,mobile,email,city,state,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?8)",params![v(row,"code"),v(row,"name"),v(row,"contact"),v(row,"mobile"),v(row,"email"),v(row,"city"),v(row,"state"),now]).map_err(err)?;},
 "equipment"=>{let cid=lookup(&tx,"clients","code",v(row,"client_code"))?.ok_or("Client missing")?;let coverage=if v(row,"coverage").is_empty(){"Out of Coverage"}else{v(row,"coverage")};tx.execute("INSERT INTO equipment(servix_equipment_id,client_id,make,model,serial_number,equipment_type,location,coverage,warranty_until,amc_until,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?11)",params![v(row,"servix_equipment_id"),cid,v(row,"make"),v(row,"model"),v(row,"serial_number"),v(row,"equipment_type"),v(row,"location"),coverage,v(row,"warranty_until"),v(row,"amc_until"),now]).map_err(err)?;},
 "service_calls"=>{let cid=lookup(&tx,"clients","code",v(row,"client_code"))?.ok_or("Client missing")?;let eid=lookup(&tx,"equipment","servix_equipment_id",v(row,"equipment_id"))?.ok_or("Equipment missing")?;let name:String=tx.query_row("SELECT name FROM clients WHERE id=?1",[cid],|r|r.get(0)).map_err(err)?;let(make,model,serial,kind,coverage):(String,String,String,String,String)=tx.query_row("SELECT make,model,serial_number,equipment_type,coverage FROM equipment WHERE id=?1",[eid],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?,r.get(3)?,r.get(4)?))).map_err(err)?;let status=if v(row,"status").is_empty(){"Open"}else{v(row,"status")};tx.execute("INSERT INTO service_calls(service_id,opened_date,client_id,equipment_id,client_name,equipment_name,make,model,serial_number,reason,complaint,engineer,status,due_date,coverage,created_by,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?17)",params![v(row,"service_id"),v(row,"opened_date"),cid,eid,name,kind,make,model,serial,v(row,"reason"),v(row,"complaint"),v(row,"engineer"),status,v(row,"due_date"),coverage,u.id,now]).map_err(err)?;let id=tx.last_insert_rowid();for(k,default)in [("priority","Normal"),("service_location",""),("coverage",coverage.as_str()),("quote_status","No Quote"),("payment_status","Pending")]{let value=if v(row,k).is_empty(){default}else{v(row,k)};tx.execute(&format!("UPDATE service_calls SET {k}=?1 WHERE id=?2"),params![value,id]).map_err(err)?;}tx.execute("UPDATE service_calls SET foc=?1 WHERE id=?2",params![["1","true","Yes"].contains(&v(row,"foc")),id]).map_err(err)?;tx.execute("INSERT INTO service_details(service_call_id,diagnosis,work_performed,testing_verification,final_result,recommendations,completion_date,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8)",params![id,v(row,"diagnosis"),v(row,"work_performed"),v(row,"testing_verification"),v(row,"final_result"),v(row,"recommendations"),v(row,"completion_date"),now]).map_err(err)?;tx.execute("UPDATE service_details SET received_condition=?1,received_accessories=?2,received_remarks=?3 WHERE service_call_id=?4",params![v(row,"received_condition"),v(row,"received_accessories"),v(row,"received_remarks"),id]).map_err(err)?;tx.execute("INSERT INTO service_followups(service_call_id,status_reason,follow_up_date) VALUES(?1,?2,?3)",params![id,v(row,"status_reason"),v(row,"follow_up_date")]).map_err(err)?;tx.execute("INSERT INTO service_events(service_call_id,event_type,note,actor_id,created_at) VALUES(?1,'Imported','Imported from validated CSV',?2,?3)",params![id,u.id,now]).map_err(err)?;},
 _=>{let id=lookup(&tx,"service_calls","service_id",v(row,"service_id"))?.ok_or("Service missing")?;tx.execute("INSERT INTO service_events(service_call_id,event_type,note,actor_id,created_at) VALUES(?1,'Note',?2,?3,?4)",params![id,v(row,"note"),u.id,format!("{} 12:00:00",v(row,"date"))]).map_err(err)?;tx.execute("INSERT INTO audit_log(entity,action,record_id,actor_id,summary,created_at) VALUES('CSV Note','Import',?1,?2,'Note imported',?3)",params![v(row,"import_key"),u.id,now]).map_err(err)?;}
 }}
 // Imported historical IDs can share a production prefix. Advance each sequence to avoid future collisions.
 for(table,column,prefix_key,next_key)in [("clients","code","client_prefix","client_next_number"),("equipment","servix_equipment_id","equipment_prefix","equipment_next_number"),("service_calls","service_id","service_prefix","service_next_number")]{
  let prefix:String=tx.query_row("SELECT value FROM settings WHERE key=?1",[prefix_key],|r|r.get(0)).map_err(err)?;
  let current:i64=tx.query_row("SELECT value FROM settings WHERE key=?1",[next_key],|r|r.get::<_,String>(0)).map_err(err)?.parse().map_err(err)?;
  let mut q=tx.prepare(&format!("SELECT {column} FROM {table}")).map_err(err)?;let values=q.query_map([],|r|r.get::<_,String>(0)).map_err(err)?;let mut next=current;
  for value in values{let value=value.map_err(err)?;if let Some(suffix)=value.strip_prefix(&prefix){if !suffix.is_empty()&&suffix.bytes().all(|b|b.is_ascii_digit()){if let Ok(n)=suffix.parse::<i64>(){next=next.max(n.checked_add(1).ok_or("Imported ID exceeds supported numbering")?);}}}}
  if next>current{tx.execute("UPDATE settings SET value=?1,updated_at=?2 WHERE key=?3",params![next.to_string(),now,next_key]).map_err(err)?;}
 }
 tx.execute("INSERT INTO audit_log(entity,action,actor_id,summary,created_at) VALUES('CSV','Import',?1,?2,?3)",params![u.id,format!("{}: {} new, {} existing skipped",d.kind,r.ready,r.skipped),now]).map_err(err)?;tx.commit().map_err(err)?;Ok(r.ready)
}
#[tauri::command] pub fn commit_csv(state:State<'_,AppState>,draft:ImportDraft,token:String)->Result<String,String>{let u=actor(&state,true)?;let mut db=state.db.lock().map_err(err)?;let r=review(&db,&draft)?;if r.token!=token||r.errors>0||r.ready==0{return Err("Preview is stale or has errors. Validate again.".into())}let safety=crate::files::safety_backup(&db,&state.database_path,"pre-import")?;let count=commit(&mut db,&u,&draft,&token)?;Ok(format!("Imported {count} new records. Safety backup: {safety}"))}
fn csv_cell(s:&str)->String{let safe=if s.trim_start().chars().next().map(|c|['=','+','-','@'].contains(&c)).unwrap_or(false){format!("'{s}")}else{s.into()};format!("\"{}\"",safe.replace('"',"\"\""))}
fn table_csv(db:&Connection,sql:&str)->Result<(String,usize),String>{let mut stmt=db.prepare(sql).map_err(err)?;let names=stmt.column_names().iter().map(|s|csv_cell(s)).collect::<Vec<_>>();let count=names.len();let mut out=format!("\u{feff}{}\r\n",names.join(","));let mut n=0;let mut rows=stmt.query([]).map_err(err)?;while let Some(r)=rows.next().map_err(err)?{let mut cells=Vec::new();for i in 0..count{let value=r.get_ref(i).map_err(err)?;let s=match value{rusqlite::types::ValueRef::Null=>String::new(),rusqlite::types::ValueRef::Integer(v)=>v.to_string(),rusqlite::types::ValueRef::Real(v)=>v.to_string(),rusqlite::types::ValueRef::Text(v)=>String::from_utf8_lossy(v).to_string(),_=>return Err("Unsupported binary column".into())};cells.push(csv_cell(&s))}out.push_str(&cells.join(","));out.push_str("\r\n");n+=1}Ok((out,n))}
#[tauri::command] pub fn export_dataset(state:State<'_,AppState>,destination:String)->Result<String,String>{let u=actor(&state,true)?;let db=state.db.lock().map_err(err)?;let dest=PathBuf::from(destination.trim());if !dest.is_absolute(){return Err("Choose an absolute export folder.".into())}let final_dir=dest.join(format!("SERVIX-export-{}",chrono::Local::now().format("%Y%m%d-%H%M%S-%f")));let pending=final_dir.with_extension("pending");fs::create_dir_all(&pending).map_err(err)?;
 let result=(||{let mut manifest=Vec::new();for(table,sql)in [
 ("clients","SELECT * FROM clients"),("equipment","SELECT e.*,c.code AS client_code FROM equipment e LEFT JOIN clients c ON c.id=e.client_id"),("service_calls","SELECT s.*,c.code AS client_code,e.servix_equipment_id AS equipment_id_code FROM service_calls s LEFT JOIN clients c ON c.id=s.client_id LEFT JOIN equipment e ON e.id=s.equipment_id"),("service_details","SELECT * FROM service_details"),("service_events","SELECT * FROM service_events"),("part_usage","SELECT * FROM part_usage"),("engineers","SELECT * FROM engineers"),("calibration_records","SELECT * FROM calibration_records"),("service_followups","SELECT * FROM service_followups"),("incoming_requests","SELECT * FROM form_intake"),("documents","SELECT * FROM attachments"),("accounts","SELECT id,username,display_name,role,active,created_at FROM users"),("audit_history","SELECT * FROM audit_log")]{let(csv,n)=table_csv(&db,sql)?;fs::write(pending.join(format!("{table}.csv")),&csv).map_err(err)?;manifest.push(json!({"file":format!("{table}.csv"),"rows":n,"sha256":hash(&csv)}));}fs::write(pending.join("manifest.json"),serde_json::to_vec_pretty(&json!({"format":"SERVIX-BUSINESS-EXPORT","version":1,"createdAt":chrono::Local::now().to_rfc3339(),"scope":"All business records","files":manifest,"note":"Document metadata only. Use recovery backup for attachment files, passwords and local configuration."})).map_err(err)?).map_err(err)?;fs::rename(&pending,&final_dir).map_err(err)?;let path=final_dir.to_string_lossy().to_string();db.execute("INSERT INTO audit_log(entity,action,actor_id,summary,created_at) VALUES('CSV','Export',?1,?2,datetime('now','localtime'))",params![u.id,json!({"scope":"Full business dataset","path":path,"files":manifest}).to_string()]).map_err(err)?;Ok(path)})();if result.is_err(){let _=fs::remove_dir_all(&pending);}result}
#[tauri::command] pub fn data_history(state:State<'_,AppState>)->Result<Vec<Value>,String>{actor(&state,true)?;let db=state.db.lock().map_err(err)?;let mut q=db.prepare("SELECT a.id,a.action,a.summary,a.created_at,u.display_name FROM audit_log a LEFT JOIN users u ON u.id=a.actor_id WHERE a.entity='CSV' ORDER BY a.id DESC LIMIT 100").map_err(err)?;let rows=q.query_map([],|r|Ok(json!({"id":r.get::<_,i64>(0)?,"action":r.get::<_,String>(1)?,"summary":r.get::<_,String>(2)?,"createdAt":r.get::<_,String>(3)?,"actor":r.get::<_,Option<String>>(4)?}))).map_err(err)?;rows.collect::<Result<Vec<_>,_>>().map_err(err)}
#[cfg(test)] mod tests{use super::*;#[test]fn csv_import_is_atomic_and_idempotent(){let mut db=Connection::open_in_memory().unwrap();crate::database::initialise(&mut db).unwrap();crate::service_detail::ensure_schema(&db).unwrap();crate::operations::ensure_schema(&db).unwrap();db.execute("INSERT INTO users(id,username,display_name,role,password_hash,created_at) VALUES(1,'admin','Admin','Administrator','hash','today')",[]).unwrap();let u=SessionUser{id:1,username:"admin".into(),display_name:"Admin".into(),role:"Administrator".into()};let d=ImportDraft{kind:"clients".into(),rows:vec![BTreeMap::from([("code".into(),"IMP-1".into()),("name".into(),"Imported Client".into())])]};let r=review(&db,&d).unwrap();assert_eq!(r.ready,1);assert_eq!(commit(&mut db,&u,&d,&r.token).unwrap(),1);let r=review(&db,&d).unwrap();assert_eq!(r.skipped,1);assert!(commit(&mut db,&u,&d,&r.token).is_err());assert_eq!(db.query_row("SELECT COUNT(*) FROM clients WHERE code='IMP-1'",[],|r|r.get::<_,i64>(0)).unwrap(),1);assert!(csv_cell("=SUM(1,2)").starts_with("\"'="));let bad=ImportDraft{kind:"equipment".into(),rows:vec![BTreeMap::from([("servix_equipment_id".into(),"EQ-1".into())])]};assert_eq!(review(&db,&bad).unwrap().errors,1);}}
#[cfg(test)] mod link_tests{
 use super::*;
 fn row(items:&[(&str,&str)])->Row{items.iter().map(|(k,v)|(k.to_string(),v.to_string())).collect()}
 #[test]fn linked_imports_and_stale_preview(){let mut db=Connection::open_in_memory().unwrap();crate::database::initialise(&mut db).unwrap();crate::service_detail::ensure_schema(&db).unwrap();crate::operations::ensure_schema(&db).unwrap();db.execute("INSERT INTO users(id,username,display_name,role,password_hash,created_at) VALUES(1,'admin','Admin','Administrator','hash','today')",[]).unwrap();let u=SessionUser{id:1,username:"admin".into(),display_name:"Admin".into(),role:"Administrator".into()};
 let d=ImportDraft{kind:"clients".into(),rows:vec![row(&[("code","C1"),("name","Client"),("mobile","9991234567")])]};let token=review(&db,&d).unwrap().token;db.execute("INSERT INTO audit_log(entity,action,created_at) VALUES('Test','Update','today')",[]).unwrap();assert!(commit(&mut db,&u,&d,&token).is_err());let token=review(&db,&d).unwrap().token;commit(&mut db,&u,&d,&token).unwrap();
 let dup=ImportDraft{kind:"clients".into(),rows:vec![row(&[("code","C2"),("name","Duplicate"),("mobile","+99 91234567")])]};assert_eq!(review(&db,&dup).unwrap().errors,1);
 let eq=ImportDraft{kind:"equipment".into(),rows:vec![row(&[("servix_equipment_id","E1"),("client_code","C1"),("make","Make"),("model","Model"),("serial_number","S1")])]};let token=review(&db,&eq).unwrap().token;commit(&mut db,&u,&eq,&token).unwrap();
 let svc=ImportDraft{kind:"service_calls".into(),rows:vec![row(&[("service_id","OLD-1"),("opened_date","2026-06-01"),("client_code","C1"),("equipment_id","E1"),("reason","Repair"),("complaint","Fault"),("status","Closed"),("final_result","Repaired"),("completion_date","2026-06-03")])]};let token=review(&db,&svc).unwrap().token;commit(&mut db,&u,&svc,&token).unwrap();
 let note=ImportDraft{kind:"notes".into(),rows:vec![row(&[("import_key","NOTE-1"),("service_id","OLD-1"),("date","2026-06-02"),("note","# Inspection\n- Checked power")])]};let token=review(&db,&note).unwrap().token;commit(&mut db,&u,&note,&token).unwrap();assert_eq!(review(&db,&note).unwrap().skipped,1);assert_eq!(db.query_row("SELECT COUNT(*) FROM pragma_foreign_key_check",[],|r|r.get::<_,i64>(0)).unwrap(),0);assert_eq!(db.query_row("SELECT final_result FROM service_details",[],|r|r.get::<_,String>(0)).unwrap(),"Repaired");let(csv,n)=table_csv(&db,"SELECT id,username,display_name,role,active FROM users").unwrap();assert_eq!(n,1);assert!(!csv.contains("password_hash"));assert_eq!(db.query_row("SELECT value FROM settings WHERE key='service_next_number'",[],|r|r.get::<_,String>(0)).unwrap(),"10001");
 }
}
#[tauri::command]pub fn record_csv_export(state:State<'_,AppState>,title:String,scope:Vec<String>,rows:usize)->Result<(),String>{let u=actor(&state,false)?;if title.len()>200||scope.len()>30||scope.iter().any(|s|s.len()>4000){return Err("Invalid export metadata".into())}let db=state.db.lock().map_err(err)?;db.execute("INSERT INTO audit_log(entity,action,actor_id,summary,created_at) VALUES('CSV','Export',?1,?2,datetime('now','localtime'))",params![u.id,json!({"scope":title,"path":"CSV download requested","rows":rows,"filters":scope}).to_string()]).map_err(err)?;Ok(())}
