const navItems:{key:ModuleKey,label:string,icon:string}[]=[
 {key:'dashboard',label:'Dashboard',icon:'dashboard'},{key:'intake',label:'Incoming Requests',icon:'intake'},{key:'service-calls',label:'Service Calls',icon:'service'},{key:'clients',label:'Clients',icon:'clients'},{key:'equipment',label:'Equipment',icon:'equipment'},{key:'engineers',label:'Engineers',icon:'engineer'},{key:'coverage',label:'Warranty / AMC',icon:'shield'},{key:'calibration',label:'Calibration',icon:'calibration'},{key:'parts',label:'Parts Used',icon:'parts'},{key:'documents',label:'Documents',icon:'documents'},{key:'reports',label:'Reports & Analytics',icon:'reports'},{key:'data',label:'Data Management',icon:'data'},{key:'users-settings',label:'Users & Settings',icon:'settings'}
];
function PlaceholderView({module}:{module:ModuleKey}){const item=navItems.find(x=>x.key===module)!;return <div className="module-content"><PageHeader title={item.label} subtitle="This clean module shell is ready for the next vertical slice."/><div className="feature-callout"><div className="feature-icon"><Icon name={item.icon} size={28}/></div><div><h2>{item.label}</h2><p>The shared SERVIX design system is already applied here. We will add the blueprint-specific workflow without creating a separate visual language for this module.</p></div></div></div>}
function LoginView({initialized,onSignedIn}:{initialized:boolean,onSignedIn:(u:SessionUser)=>void}){const [setup,setSetup]=React.useState(!initialized);const [username,setUsername]=React.useState('');const [displayName,setDisplayName]=React.useState('Administrator');const [password,setPassword]=React.useState('');const [error,setError]=React.useState('');const [busy,setBusy]=React.useState(false); const go=async()=>{setBusy(true);setError('');try{const u=setup?await ServixApi.createFirstAdmin(username,password,displayName):await ServixApi.authenticate(username,password);onSignedIn(u)}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}};return <div className="login-screen"><section className="login-card"><div className="login-brand"><div className="brand-mark brand-logo"><img src="assets/servix-login-mark.png" alt="SERVIX"/></div><div><strong>SERVIX</strong><span>SERVICE MANAGEMENT</span></div></div><div className="login-copy"><h1>{setup?'Create administrator':'Welcome back'}</h1><p>{setup?'Set up the first local administrator account for this SERVIX installation.':'Sign in to your local SERVIX workspace.'}</p></div>{setup&&<Field label="Display Name"><input value={displayName} onChange={e=>setDisplayName(e.target.value)}/></Field>}<Field label="Username" required><input autoFocus value={username} onChange={e=>setUsername(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go()}/></Field><Field label="Password" required><input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go()}/></Field>{error&&<div className="form-error">{error}</div>}<button className="primary-button login-button" disabled={busy} onClick={go}>{busy?'Please wait...':setup?'Create Administrator':'Sign In'}</button>{initialized&&<small className="login-foot">Standalone • Offline-first • Local database</small>}</section></div>}
function App(){const [status,setStatus]=React.useState(null as SystemStatus|null);const [user,setUser]=React.useState((isDesktop?null:mockUser) as SessionUser|null);const [data,setData]=React.useState(null as DashboardData|null);const [module,setModule]=React.useState('dashboard' as ModuleKey);const [collapsed,setCollapsed]=React.useState(false);const [globalSearch,setGlobalSearch]=React.useState('');const [toast,setToast]=React.useState('');const [syncWarningDismissed,setSyncWarningDismissed]=React.useState(false);
 const refresh=React.useCallback(async()=>{try{setData(await ServixApi.bootstrap())}catch(e:any){setToast(e?.message||String(e))}},[]);
 React.useEffect(()=>{ServixApi.systemStatus().then(setStatus).catch(e=>setToast(String(e)))},[]);
 React.useEffect(()=>{if(user)refresh()},[user]);
 const sync=async()=>{try{const s=await ServixApi.syncGoogleForm();setData((d:any)=>d?({...d,sync:s}):d);setToast(s.message);setTimeout(()=>setToast(''),3200)}catch(e:any){setToast(e?.message||String(e))}};
 if(!status)return <div className="boot-screen"><div className="boot-spinner"/><strong>Starting SERVIX…</strong></div>;
 if(!user)return <LoginView initialized={status.initialized} onSignedIn={setUser}/>;
 if(!data)return <div className="boot-screen"><div className="boot-spinner"/><strong>Loading workspace…</strong></div>;
 const content=module==='dashboard'?<DashboardView data={data} onNavigate={setModule} onSync={sync}/>:module==='intake'?<IntakeView data={data} onRefresh={refresh} onSync={sync}/>:module==='service-calls'?<ServiceCallsView data={data} onRefresh={refresh}/>:module==='clients'?<ClientsView data={data}/>:module==='equipment'?<EquipmentView data={data}/>:module==='engineers'?<EngineersView/>:module==='coverage'?<CoverageView data={data}/>:module==='calibration'?<CalibrationView data={data}/>:module==='parts'?<PartsView data={data}/>:module==='documents'?<DocumentsView/>:module==='reports'?<ReportsView data={data}/>:module==='data'?<DataManagementView/>:module==='users-settings'?<SettingsView data={data} onRefresh={refresh}/>:<PlaceholderView module={module}/>;
 return <div className={`app-shell ${collapsed?'sidebar-collapsed':''}`}><aside className="sidebar"><div className="sidebar-brand"><button className="brand-mark brand-logo" onClick={()=>setCollapsed(!collapsed)} title="Toggle navigation"><img src="assets/servix-sidebar-logo.png" alt="SERVIX"/></button><div className="brand-copy"><strong>SERVIX</strong><span>SERVICE MANAGEMENT</span></div></div><nav>{navItems.map(item=><button key={item.key} className={module===item.key?'active':''} onClick={()=>setModule(item.key)} title={item.label}><Icon name={item.icon}/><span>{item.label}</span>{item.key==='intake'&&data.intake.filter(x=>x.status==='New').length>0&&<b>{data.intake.filter(x=>x.status==='New').length}</b>}</button>)}</nav><div className="sidebar-footer"><span>v0.1.0 Rebuild</span><small>Tauri • React • SQLite</small></div></aside><main className="workspace"><header className="topbar"><div className="global-search"><Icon name="search"/><input value={globalSearch} onChange={e=>setGlobalSearch(e.target.value)} placeholder="Search Service ID, Client, Equipment..."/></div><div className="top-actions"><button className="icon-button"><Icon name="bell"/></button><div className="user-menu"><span className="avatar">{(user.displayName||user.username).slice(0,1).toUpperCase()}</span><span><strong>{user.displayName}</strong><small>{user.role}</small></span></div><button className="text-button" onClick={async()=>{await ServixApi.logout();setUser(null)}}>Sign out</button></div></header><div className="content-scroll">{content}</div></main>{data.sync.status==='overdue'&&!syncWarningDismissed&&<Modal title="Google Form Sync Overdue" subtitle="More than 24 hours have passed since the last successful intake sync." onClose={()=>setSyncWarningDismissed(true)} footer={<><button className="secondary-button" onClick={()=>setSyncWarningDismissed(true)}>Dismiss</button><button className="primary-button" onClick={async()=>{await sync();setSyncWarningDismissed(true)}}><Icon name="refresh"/> Sync Now</button></>}><div className="sync-warning-copy"><Icon name="bell" size={24}/><p>New Google Form service requests may be waiting. Normal SERVIX work remains available even if the internet or Google source is unavailable.</p></div></Modal>}{toast&&<div className="toast">{toast}</div>}</div>;
}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
