type SearchTarget={kind:'service'|'client'|'equipment'|'intake';id:number;title:string;subtitle:string;detail:string;status:string;score:number};
function searchText(value:string){return String(value||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function searchWorkspace(data:DashboardData,query:string):SearchTarget[]{
 const text=searchText(query);const tokens=text.split(/\s+/).filter(Boolean);if(!text||!/[\p{L}\p{N}]/u.test(text))return [];
 const clientsById=new Map(data.clients.map(c=>[c.id,c]));const equipmentById=new Map(data.equipment.map(e=>[e.id,e]));const clientsByName=new Map<string,ClientRecord[]>();data.clients.forEach(c=>clientsByName.set(c.name,[...(clientsByName.get(c.name)||[]),c]));
 const results:SearchTarget[]=[];
 const add=(kind:SearchTarget['kind'],id:number,title:string,subtitle:string,detail:string,status:string,extra:string)=>{const fields=[title,subtitle,detail,extra].map(searchText);const all=fields.join(' ');const compact=all.replace(/[^\p{L}\p{N}]/gu,'');if(!tokens.every(t=>all.includes(t)||compact.includes(t.replace(/[^\p{L}\p{N}]/gu,''))))return;const titleText=fields[0];const score=(titleText===text?100:titleText.startsWith(text)?70:fields.some(f=>f===text)?60:30)+(kind==='service'?5:0);results.push({kind,id,title,subtitle,detail,status,score})};
 data.services.forEach(s=>{const legacy=clientsByName.get(s.client);const c=s.clientId!=null?clientsById.get(s.clientId):legacy?.length===1?legacy[0]:undefined;const eq=equipmentById.get(s.equipmentId);add('service',s.id,s.serviceId,s.client+' • '+s.equipment,[s.serialNumber,s.reason,s.engineer].filter(Boolean).join(' • '),s.status,[s.make,s.model,s.complaint,c?.contact,c?.email,c?.mobile,eq?.servixEquipmentId].filter(Boolean).join(' '))});
 data.clients.forEach(c=>add('client',c.id,c.name,c.code+' • '+[c.city,c.state].filter(Boolean).join(', '),[c.contact,c.mobile,c.email].filter(Boolean).join(' • '),c.active?'Active':'Inactive',''));
 data.equipment.forEach(e=>add('equipment',e.id,e.servixEquipmentId,[e.make,e.model].filter(Boolean).join(' ')+' • '+e.client,'S/N '+(e.serialNumber||'—')+' • '+e.type,e.coverage,e.location));
 data.intake.forEach(i=>add('intake',i.id,i.client,'Incoming request #'+i.id+' • '+i.equipment,[i.contact,i.mobile,i.email].filter(Boolean).join(' • '),i.status,[i.make,i.model,i.serialNumber,i.complaint,i.linkedServiceId].filter(Boolean).join(' ')));
 return results.sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title)||a.id-b.id);
}
function loadDisplayScale():number{try{return localStorage.getItem('servix-display-scale')==='100'?100:125}catch{return 125}}
function applyDisplayScale(scale:number){document.documentElement.style.fontSize=(16*scale/100)+'px';document.documentElement.dataset.displayScale=String(scale)}
applyDisplayScale(loadDisplayScale());
function DisplayPreferences(){const [scale,setScale]=React.useState(loadDisplayScale());return <section className="card display-preferences"><h3>Display & Readability</h3><p>Choose the size of SERVIX text and controls. The layout adapts to your window and Windows display scaling.</p><div className="display-options">{[100,125].map(v=><button type="button" aria-pressed={scale===v} className={scale===v?'active':''} key={v} onClick={()=>{setScale(v);try{localStorage.setItem('servix-display-scale',String(v))}catch{}applyDisplayScale(v)}}><Icon name="settings" size={20}/><strong>{v}%</strong><span>{v===125?'Comfortable • Default':'Compact'}</span></button>)}</div><small>Saved on this computer. Changes apply immediately to every screen and popup.</small></section>}
function UniversalSearch({data,onSelect}:{data:DashboardData;onSelect:(target:SearchTarget)=>void}){
 const [query,setQuery]=React.useState('');const [open,setOpen]=React.useState(false);const [active,setActive]=React.useState(0);const host=React.useRef(null);
 const matches=React.useMemo(()=>searchWorkspace(data,query),[data,query]);const results=matches.slice(0,24);
 React.useEffect(()=>{const close=(e:MouseEvent)=>{if(host.current&&!host.current.contains(e.target))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 React.useEffect(()=>{host.current?.querySelector('[aria-selected="true"]')?.scrollIntoView({block:'nearest'})},[active]);
 const choose=(r:SearchTarget)=>{onSelect(r);setOpen(false);setQuery('');setActive(0)};
 return <div className="global-search universal-search" ref={host}><Icon name="search"/><input role="combobox" aria-label="Search all SERVIX records" aria-autocomplete="list" aria-expanded={open&&!!query.trim()} aria-controls="workspace-search-results" aria-activedescendant={open&&results[active]?'workspace-result-'+active:undefined} value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true);setActive(0)}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);return}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setOpen(true);setActive(a=>results.length?(a+(e.key==='ArrowDown'?1:-1)+results.length)%results.length:0)}if(e.key==='Enter'&&results[active]){e.preventDefault();choose(results[active])}}} placeholder="Search IDs, client, phone, email, equipment or serial…"/>{open&&query.trim()&&<div className="search-suggestions"><div className="search-suggestions-head"><strong>{matches.length} matching records</strong><small>↑ ↓ choose • Enter open</small></div><div role="listbox" id="workspace-search-results">{results.map((r,i)=><button type="button" role="option" aria-selected={i===active} id={'workspace-result-'+i} className={i===active?'active':''} key={r.kind+'-'+r.id} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(r)}><span className={'search-result-icon '+r.kind}><Icon name={r.kind==='client'?'clients':r.kind==='intake'?'intake':r.kind==='equipment'?'equipment':'service'} size={21}/></span><span className="search-result-copy"><strong>{r.title}</strong><span>{r.subtitle}</span><small>{r.detail}</small></span><span className="search-result-kind">{r.kind==='service'?'Service Call':r.kind==='client'?'Client':r.kind==='equipment'?'Equipment':'Incoming'}<StatusBadge value={r.status}/></span></button>)}{!results.length&&<p className="search-no-results">No matches. Try a Service ID, phone, email or serial number.</p>}</div>{matches.length>24&&<p className="search-no-results">Showing the first 24 matches. Type more detail to narrow the results.</p>}</div>}</div>;
}
function LinkedServiceTable({rows,onOpen}:{rows:ServiceCall[];onOpen?:(s:ServiceCall)=>void}){return <div className="linked-service-table"><div className="linked-service-head"><span>Service ID / Date</span><span>Equipment / Reason</span><span>Status</span></div>{rows.map(s=><button type="button" key={s.id} disabled={!onOpen} onClick={()=>onOpen?.(s)}><span><strong>{s.serviceId}</strong><small>{s.openedDate}</small></span><span><strong>{s.equipment}</strong><small>{s.reason}{s.serialNumber?' • S/N '+s.serialNumber:''}</small></span><StatusBadge value={s.status}/></button>)}{!rows.length&&<p className="quiet-empty">No Service Calls for this selection.</p>}</div>}
function NoteContent({text}:{text:string}){return <div className="formatted-note">{text.split('\n').map((line,i)=>line.startsWith('# ')?<h4 key={i}>{line.slice(2)}</h4>:/^[-•]\s/.test(line)?<div className="note-bullet" key={i}><span>•</span><span>{line.replace(/^[-•]\s/,'')}</span></div>:/^\d+\.\s/.test(line)?<div className="note-bullet" key={i}><strong>{line.match(/^\d+\./)?.[0]}</strong><span>{line.replace(/^\d+\.\s/,'')}</span></div>:<p key={i}>{line||'\u00a0'}</p>)}</div>}
function HistoryTimeline({events}:{events:EntityHistoryEvent[]}){
 const groups=new Map<number,EntityHistoryEvent[]>();events.forEach(e=>groups.set(e.serviceCallId,[...(groups.get(e.serviceCallId)||[]),e]));
 return <div className="grouped-history">{Array.from(groups.entries()).map(([id,items])=><section className="history-service-group" key={id}><header><span><strong>{items[0].serviceId}</strong><small>{items[0].equipment+(items[0].serialNumber?' • S/N '+items[0].serialNumber:'')}</small></span><StatusBadge value={items[0].serviceStatus}/></header>{items.map(ev=>{const dt=splitAuditDateTime(ev.createdAt);return <div className="history-event-line" key={ev.id}><div><strong>{dt.date}</strong><small>{dt.time}</small></div><div><strong>{ev.eventType}</strong><NoteContent text={historyEventDetails(ev)}/><small>{ev.actor+' • '+ev.reason}</small></div></div>})}</section>)}{!events.length&&<p className="quiet-empty">No history recorded for this selection yet.</p>}</div>;
}

function historyEventDetails(ev:{note:string;oldValue:string;newValue:string}){const change=(ev.oldValue||ev.newValue)?[ev.oldValue||'—',ev.newValue||'—'].join(' → '):'';return [ev.note,change&&change!==ev.note?change:''].filter(Boolean).join('\n')||'Record activity'}
